### ISSUE TITLE
Template helpers

### ISSUE THREAD

**Issue by apexys** [SergioBenitez/Rocket#771] opened 2018-09-11 15:46 UTC
Hi,
I'm currently trying to use handlebars templates in a rocket project.
The rust crate for handlebars that is used in the `rocket_contrib` crate allows for the registration of so-called helper-functions that one can call from the template code itself, for example to compare strings or to insert the current date and time.
As far as I can see, there's no way to currently do add one through the existing fairing code, since
I can't get access to the underlying `Context`-element that contains the engine through the managed state, because it's not publically exported (at least not in version 0.3.16).
I'm not sure what the best way to approach this would be.
Since helper functions exist in Tera templates as well, maybe the necessary infrastructure could be shared?

**Comment by nCrazed** [comment] 2018-09-11 15:55
This looks like a duplicate of #63

**Comment by jebrosen** [comment] 2018-09-11 18:03
Yes, this is a duplicate of #63 and #64. It was resolved in #521 and the functionality is present in master. It will be in the 0.4 release as well.

**Closed by jebrosen** 2018-09-11 18:03 UTC

**Comment by apexys** [comment] 2018-09-11 18:15
Nice, thank you!
