### ISSUE TITLE
[Feature Request]Reload all templates for every Template::render() call at debug mode.

### ISSUE THREAD

**Issue by zoumi** [SergioBenitez/Rocket#523] opened 2017-12-28 14:43 UTC
It's disturbing to restart server after the templates changed.

**Comment by zoumi** [comment] 2017-12-28 14:49
Maybe we can achieve this by:

```
impl Responder<'static> for Template {
    fn respond_to(self, req: &Request) -> response::Result<'static> {
        let ctxt = req.guard::<State<Context>>().succeeded().ok_or_else(|| {
            error_!("Uninitialized template context: missing fairing.");
            info_!("To use templates, you must attach `Template::fairing()`.");
            info_!("See the `Template` documentation for more information.");
            Status::InternalServerError
        })?;
        #[cfg(debug_assertions)]
        let (render,content_type) = {
            match Context::initialize(&ctxt.root) {
                Some(ctxt) => self.finalize(&ctxt)?;
                None => {
                    error_!("The template context failed to initialize.");
                    return Status::InternalServerError;
                }
            }
        };
        #[cfg(not(debug_assertions))]
        let (render, content_type) = self.finalize(&ctxt)?;
        Content(content_type, render).respond_to(req)
    }
}
```

**Comment by jebrosen** [comment] 2017-12-28 15:49
Heads-up: this proposed solution to re-initialize the context will be bad to combine with #521, as it destroys all state including registered helpers. For example, `Handlebars::register_helper` and `Handlebars::register_template_string` that should be preserved between renders.

Ideas (spitballing here):
* Use `Handlebars::template_render` at render time, probably in `finalize`, instead of registering the templates. This only solves editing existing template files, as new templates will not be scanned for again.
* Re-run the whole filesystem search every time a template is requested, to pick up newly added files.
* Warn that `Template::custom` and live-reload are incompatible. This feature disparity would be quite unfortunate, though.
* Is `debug_assertions` really the right way to decide this? Other options might include environment (Dev, Staging, Prod) or a configuration setting.

I am not familiar with Tera, but I imagine everything I said about Handlebars has an equivalent concept there.

**Comment by SergioBenitez** [comment] 2017-12-28 17:35
I believe this is a duplicate of #163.

**Closed** 2017-12-28 17:48 UTC
Labels: duplicate

**Comment by zoumi** [comment] 2017-12-29 14:46
Tested with my fork! Works as expected.

```rust
impl Responder<'static> for Template {
    fn respond_to(self, req: &Request) -> response::Result<'static> {
        let ctxt = req.guard::<State<Context>>().succeeded().ok_or_else(|| {
            error_!("Uninitialized template context: missing fairing.");
            info_!("To use templates, you must attach `Template::fairing()`.");
            info_!("See the `Template` documentation for more information.");
            Status::InternalServerError
        })?;
        #[cfg(debug_assertions)]
        let (render,content_type) = {
            match Context::initialize(ctxt.root.clone()) {
                Some(ctxt) => {self.finalize(&ctxt)?}
                None => {
                    error_!("The template context failed to initialize.");
                    return Err(Status::InternalServerError);
                }
            }
        };
        #[cfg(not(debug_assertions))]
        let (render, content_type) = self.finalize(&ctxt)?;
        Content(content_type, render).respond_to(req)
    }
}
```

**Comment by SergioBenitez** [comment] 2017-12-29 17:32
@zoumi It's not acceptable to discard modifications made in `Template::custom()` to enable this feature, and your code does this by rebuilding the `Context` from scratch without accounting for the user's changes. Furthermore, it would be nice if an implementation would first check if there's a need to reload the context and only then perform a full reload.

If we store the function passed in by the user in `custom()`, we can then re-run it when we regenerate the `Context`. I believe what we should do is as follows:

  1. Amend `Context` to contain the user's customization function, if any.

  2. On `#[cfg(dev)]`, store a `RwLock<Context>` instead of a `Context` in managed state. Accessing the `Context` should be abstracted away so most of the code knows no better.

  3. On `#[cfg(dev)]`, add a request fairing that:
    a. Checks to see if any templates have changed.
    b. If so, recreates the `Context` and replaces the existing context.

The changes to do this should be fairly minimal. I'd be happy to review a PR that does this.
