### ISSUE TITLE
Extend guide for database usage

### ISSUE THREAD

**Issue by stonymahony** [SergioBenitez/Rocket#1002] opened 2019-05-13 15:22 UTC
Hello,

I'm new to Rust and Rocket and stuck completely by connecting to a database.
The official guide is quite superficial at this point in my opinion and I assume I'm not the only one with problems by setting up database connection.

That's why I suggest to extend the guide with an example for each database.
Furthermore I would appreciate any help for my described errors.

## System
Windows 10 Pro, Visual Studio Build Tools 2019

### MongoDB
Cargo.toml
```
[dependencies]
rocket = "0.4.1"
rocket_contrib = {version = "0.4.1", features = ["mongodb_pool"]}
mongodb = "0.3.12"
openssl = { version = "0.10.22", vendored = "true" }
openssl-sys = "0.9.46"
```

#### Compilation Errors:
**linking with `link.exe` failed: exit code: 1120
error LNK2019: Link to not resolved symbol ...**

This is definitely caused by mongodb/openssl.

###MySQL
Cargo.toml
```
[dependencies]
rocket = "0.4.1"
rocket_contrib = {version = "0.4.1", default-features = false, features = ["diesel_mysql_pool"]}
mysql = "16.0.2"
```

#### Compilation Errors:
could not find native static library `mysqlclient`, perhaps an -L flag is missing?

## Conclusion
It seems that the steps described in the guide are not enough to succeed on an average Windows PC.
I tried to install some libraries manually, as supposed by error messages (openssl, openssl-sys, libmysql, mysql-sys), but it is still not working.

**Comment by jebrosen** [comment] 2019-05-14 05:33
The general first:

Rocket will not be able to keep up with documenting details of every database driver; the connection pooling support in `rocket_contrib` is essentially a convenience. A few other similar issues have been opened, though, and we can definitely do better about specifying which versions of database engines are supported and where their respective documentation lies.

---

As for your specific issues:

> Windows 10 Pro, Visual Studio Build Tools 2019

In the past, we have not done very little testing on Windows. We want to fix that, though! See #801.

> I tried to install some libraries manually, as supposed by error messages (openssl, openssl-sys, libmysql, mysql-sys), but it is still not working.

Both of those errors point to something not being installed or configured, something I also struggled with when I tried testing on Windows in the past.

In the case of `openssl`, it's not needed by default and it looks like you haven't activated it on `mongodb` anyway (https://github.com/mongodb-labs/mongo-rust-driver-prototype#importing). You should either use `mongodb = { ..., features = ["ssl"] }` or not use `openssl` if you don't need it. All that being said, your dependency specification for `openssl` looks right according to the documentation so I'm not sure what the linking problem is. If you post more of the error message I might have a better idea.

For `diesel` with `mysql`, documentation for the low-level library is at https://github.com/sgrif/mysqlclient-sys#building. It looks like you need the MySQL server installed and maybe need to add something to your system PATH so that `mysqlclient-sys` can detect it. `diesel` doesn't even use the `mysql` crate, so try removing that too in case it's the problem here.

**Comment by kanarok** [comment] 2019-07-28 15:59
Well a bit more of documentation would be nice. Connecting for me was fairly easy using the guide. Now I'm trying to figure out a way to do a simple query (MySQL btw). All the examples I've found so far omit the use rocket_contrib::databases::diesel; but do a #[macro_use] extern crate diesel;
I guess I will come to a successful query with that. But at least one working (not generic) example to query a db would be great. Because it feels like those examples are missing some unknown point.

This was the one useful and recent I've found:
https://cprimozic.net/blog/rust-rocket-cloud-run/

**Comment by jebrosen** [comment] 2019-07-28 16:48
Minor update: openssl is brought in via `r2d2-mongodb`, which doesn't make `ssl` support optional.

---

I'm going to close this issue, because it's mostly a duplicate of #950 and/or problems with dependencies outside of rocket's control. Let's keep overall discussion of database documentation in that issue.

**Closed by jebrosen** 2019-07-28 16:48 UTC
Labels: docs, question
