### ISSUE TITLE
Response gets cut using tls12

### ISSUE THREAD

**Issue by BlackDex** [SergioBenitez/Rocket#1167] opened 2019-11-08 23:13 UTC
## Bug Report

Rocket Version: 0.5.0-dev multiple commit revisions.
OS: Multiple, Ubuntu, Arch, Raspberry PI etc...

With bitwarden_rs, we use Rocket as a web framework. We received quite a few reports about issues with a latest release of the bitwarden android client.

I discovered that for some reason it was using tls12 instead of tls13 used by the previous version.

This seems to trigger a bug which caucus to cut some transmissions prematurely. This can be tested by setting a browser to not support tls13, like setting tls.max to 3 in Firefox.

For some more (bit scattered) info check the issue at bitwarden_rs: https://github.com/dani-garcia/bitwarden_rs/issues/687 .

The difference between the suites that are used.
v2.2.2 works, v2.2.6 triggers (sometimes) an error.

v2.2.2: [rustls::server::hs][DEBUG] decided upon suite SupportedCipherSuite { suite: TLS13_AES_128_GCM_SHA256, kx: BulkOnly, bulk: AES_128_GCM, hash: SHA256, sign: Anonymous, enc_key_len: 16, fixed_iv_len: 12, explicit_nonce_len: 0 }

v2.2.6: [rustls::server::hs][DEBUG] decided upon suite SupportedCipherSuite { suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, kx: ECDHE, bulk: AES_128_GCM, hash: SHA256, sign: RSA, enc_key_len: 16, fixed_iv_len: 4, explicit_nonce_len: 8 }

I also discussed this with @jebrosen on matrix/irc.

**Comment by jebrosen** [comment] 2019-11-09 02:34
Okay, at least part of this is easily reproducible in the existing `tls` example in `master` with Firefox:

* `security.version.tls.max` = 4 (current default): OK, selects TLS 1.3
* `security.version.tls.max` = 3: OK, selects TLS 1.2
* `security.version.tls.max` = 2: Fails - server says `Warning: Sending fatal alert ProtocolVersion`; Firefox reports `Error code: SSL_ERROR_PROTOCOL_VERSION_ALERT` and a message and button suggesting to change the network security settings back to the defaults.

The logs for v2.2.6 don't say what version of TLS was chosen, only that it wasn't 1.3. If the client requires anything less than 1.2, that would explain why this error is appearing as `rustls` only supports 1.2 and 1.3. I don't have any idea for

> (sometimes) an error.

other than that the unaffected users might be running behind a proxy like nginx configured to support a wider range of TLS versions. It is a bit surprising however that a newer client would "lose" the ability to use a newer version of TLS, and that I have no explanation for.

Can you tell (perhaps after raising the logging level) exactly which version of TLS is being selected by the v2.2.6 client?

**Comment by BlackDex** [comment] 2019-11-09 10:37
I have enabled trace logging and did some more testing with curl also this time.
I only get half pages and errors using Firefox `security.version.tls.max = 3` and the app.
With curl, using the same cipher suite and tls12 it works. But there is a difference.

Curl has other "**namedgroups**" and "**ecpoints**", which i wasn't able to change i think.
See the attachment with the results.

[rocket-tls-issue-1167.txt](https://github.com/SergioBenitez/Rocket/files/3827165/rocket-tls-issue-1167.txt)

**Comment by jebrosen** [comment] 2019-11-09 15:58
> I only get half pages and errors using Firefox `security.version.tls.max = 3` and the app.

Okay, that is interesting. From these logs and your description of "cut" responses, the handshake looks fine and then something breaks the connection partway through. Is there a publicly visible test server I can try with (e.g. the host in those logs?), since I have not actually been able to reproduce that issue.

@ctz, does this sound at all familiar? I believe this is occurring with rustls `0.15` via hyper-sync-rustls `0.3.0-rc.5`

**Comment by BlackDex** [comment] 2019-11-09 16:03
@jebrosen i have a system for this running.
Check https://bwrsdev.vyus.nl:39090 .
This is also where in firefox i get that the page is not loading correctly.

**Comment by jebrosen** [comment] 2019-11-09 16:12
I get intact responses with both firefox and curl using the same parameters as in the log file you posted, so this could be a client-side issue. What operating system and version and version of firefox and curl/openssl are you using on the client side?

**Comment by BlackDex** [comment] 2019-11-09 16:13
That is indeed strange. As I'm also not the only one. Let me check in a few seconds

**Comment by BlackDex** [comment] 2019-11-09 16:27
I am running Firefox 71.0b7 on Arch Linux Using NSSSSL v3.47.
OpenSSL 1.1.1d  10 Sep 2019.

curl --version
curl 7.66.0 (x86_64-pc-linux-gnu) libcurl/7.66.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.8.2 nghttp2/1.39.2
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

**Comment by ctz** [comment] 2019-11-09 16:30
> @ctz, does this sound at all familiar?

This isn't a bug I've seen before. @BlackDex if you could capture a pcap (using wireshark/tcpdump) of an affected transfer that might be illuminating.

**Comment by BlackDex** [comment] 2019-11-09 16:33
@ctz, decrypted or not?

**Comment by ctz** [comment] 2019-11-09 16:38
Un-decrypted should be sufficient at this point.

**Comment by BlackDex** [comment] 2019-11-09 16:51
Here is a pcap, and a screenshot of the result i got.

[tls12-issue-1167.pcapng.gz](https://github.com/SergioBenitez/Rocket/files/3827500/tls12-issue-1167.pcapng.gz)
![tls12-issue-1167_firefox-screenshot](https://user-images.githubusercontent.com/610450/68532054-7b8b1680-0319-11ea-87ae-7d5a6666e4bc.png)

**Comment by BlackDex** [comment] 2019-11-09 17:06
And just in case this helps better, a decrypt-able version:

[02-tls12-issue-1167-decryptable.pcapng.gz](https://github.com/SergioBenitez/Rocket/files/3827509/02-tls12-issue-1167-decryptable.pcapng.gz)
[02-tls12-issue-1167-sslkeylog.log.gz](https://github.com/SergioBenitez/Rocket/files/3827510/02-tls12-issue-1167-sslkeylog.log.gz)
![02-tls12-issue-1167_firefox-screenshot](https://user-images.githubusercontent.com/610450/68532272-9eb6c580-031b-11ea-99dc-3c7ecc865f3b.png)

**Comment by ctz** [comment] 2019-11-09 17:53
Well, this is strange. For one of the affected transfers:

- the client asks for the connection to be kept open with `connection: keep-alive`
- it seems all the data is sent in the response (no decryption failures according to wireshark or spurious tcp resets during the transfer)
- he last TLS appdata record is a TCP segment with FIN set. I guess the server has decided not to honour the keep-alive request, which it is allowed to do. However, it should have sent a TLS close notify here in the last record.
- the client responds with a TLS close notify
- followed by a clean TCP close

At a complete guess, then, I think firefox is unhappy with the lack of the TLS close notify on these transfers. These are generally present on other transfers, though, so perhaps we're losing the outgoing close notify on these transfers because the send window is full?

**Comment by BlackDex** [comment] 2019-11-09 17:57
That could explain why it happens some times and not always i think.
And also why it could happen more during an actual login/sync of the data from the server to the client which could have large blob of data.

Is there anything we can do to stop this? Disable keep-alive or something?

**Comment by jebrosen** [comment] 2019-11-09 18:06
Keep-alive has some known issues and disabling it is not a terrible idea. AFAIK nobody has figured out which issues are in the old version of hyper we use and which are in Rocket. I would not be surprised to see #1065 fix this by using the latest version of hyper, and if not we will at least be working with recently maintained code.

**Comment by BlackDex** [comment] 2019-11-09 18:15
I just tried disabling keep-alive, had no effect.

**Comment by BlackDex** [comment] 2019-11-09 18:45
If you have any ideas left which we could try?

In any case i did appreciated the help and quick response.

**Comment by BlackDex** [comment] 2019-11-09 22:51
@ctz / @jebrosen : We tested an async version, and that seems to solve the issues.
We have to figure out some quirks with multipart which didn't seem to compile for use.
And we are a hesitant to push it to our master branch until Rocket async is pushed to master.

**Comment by jebrosen** [comment] 2019-11-09 23:58
Yeah, I predict the `async` branch will change enough that you don't want to do that just yet.

The next step as far as reproduction would be to try with only `hyper` + `hyper_sync_rustls`, to make sure it's not something specific to Rocket. It's frustrating that I can not reproduce it myself despite running the same version of Firefox.

**Comment by dani-garcia** [comment] 2019-11-10 14:06
It seems you might be right @jebrosen, I created a new branch using rocket's `async` branch and it seems to solve the issue at least for the tests @BlackDex did when we talked in the Matrix channel.

I posted a message in the original issue hoping some more users test it, we'll see how it goes.

PD: The migration to async was suprisingly easy, there was no changes needed on the routes other than when involving the multipart crate, which doesn't seem compatible at the moment.
The changes to Fairings and Responders mostly consisted of wrapping stuff in `Box::pin(async move {` and changing the functions signature. Overall I had a harder time updating Ring than Rocket, great job there!
https://github.com/dani-garcia/bitwarden_rs/compare/async

**Comment by jebrosen** [comment] 2019-11-10 18:24
> PD: The migration to async was suprisingly easy, there was no changes needed on the routes other than when involving the multipart crate, which doesn't seem compatible at the moment.
The changes to Fairings and Responders mostly consisted of wrapping stuff in Box::pin(async move { and changing the functions signature. Overall I had a harder time updating Ring than Rocket, great job there!

Glad to hear it; relatively painless upgrades was one of the goals. I know body reading such as `multipart` will be more difficult to port, and I don't know which multipart crates if any support asynchronous input streams yet. If buffering the data in memory is safe (i.e. a fairly small limit), something along the lines of `let buffer = Vec::with_capacity(something); data.open().take(input_limit).read_all(&mut buffer).await;` might work.

I do hope to be able to use `async_trait`, in which case upgrading Responder would instead require a macro (e.g. `#[rocket::async_trait]`) and `fn -> async fn`.

**Comment by SergioBenitez** [comment] 2021-02-26 10:27
It looks like this is resolved on `master`, is that right? I'm closing on the assumption that this is right, but please feel free to correct me.

**Closed by SergioBenitez** 2021-02-26 10:27 UTC
Labels: upstream
