### ISSUE TITLE
Not clear compiling error detail on json! macro

### ISSUE THREAD

**Issue by jasl** [SergioBenitez/Rocket#836] opened 2018-11-20 05:23 UTC
I'm using the latest Rocket, trying to build a API (which output Json)

In the API, I need to call an external Json API, the code looks like:
```rust
#[get("/test")]
fn test() -> JsonValue {
    let mut input = serde_json::Map::new();
    input.insert("name".to_string(), json!("David".to_string()));
    // do Json RPC
    // render Json
```

it will failed to compile, because 

```
 --> <::rocket_contrib::json::json macros>:2:1                                                                                                  
  |                                                                                                                                             
2 | / $ crate :: json :: JsonValue (                                                                                                            
3 | | $ crate :: json :: json_internal ! ( $ ( $ json ) + ) ) } ;                                                                               
  | |_______________________________________________________^ expected enum `serde_json::Value`, found struct `rocket_contrib::json::JsonValue` 
  |                                                                                                                                             
  = note: expected type `serde_json::Value`                                                                                                     
             found type `rocket_contrib::json::JsonValue` 
```

the message doesn't contains which line trigger the problem, it triggered by `input.insert("name".to_string(), json!("David".to_string()));`

It seems Rocket has its own `json!` macro which not compatible with serde_json.

the fix is simple, I just change it to `json!("David".to_string().0`.

but it's there any chance to improve the compiling message?

**Comment by jebrosen** [comment] 2018-11-20 05:45
What version of Rocket and rustc was this with? If it's not the latest rustc, is it still a problem if you compile with the latest nightly?

This is what I got, with `rustc 1.32.0-nightly (f37247f88 2018-11-17)`:

```
error[E0308]: mismatched types
  --> examples/json/src/main.rs:30:38
   |
30 |     input.insert("name".to_string(), json!("David".to_string()));
   |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `serde_json::value::Value`, found struct `rocket_contrib::json::JsonValue`
   |
   = note: expected type `serde_json::value::Value`
              found type `rocket_contrib::json::JsonValue`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

This might be a duplicate of #811, in which case the code in `// do Json RPC // render Json` could be causing the line numbers not show up.

**Comment by jasl** [comment] 2018-11-20 07:34
> What version of Rocket and rustc was this with? If it's not the latest rustc, is it still a problem if you compile with the latest nightly?
> 
> This is what I got, with `rustc 1.32.0-nightly (f37247f88 2018-11-17)`:
> 
> ```
> error[E0308]: mismatched types
>   --> examples/json/src/main.rs:30:38
>    |
> 30 |     input.insert("name".to_string(), json!("David".to_string()));
>    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `serde_json::value::Value`, found struct `rocket_contrib::json::JsonValue`
>    |
>    = note: expected type `serde_json::value::Value`
>               found type `rocket_contrib::json::JsonValue`
>    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
> ```
> This might be a duplicate of #811, in which case the code in `// do Json RPC // render Json` could be causing the line numbers not show up.

I use rustc 1.31.0-nightly (96cafc53c 2018-10-09), I'll try latest rustc later

**Comment by SergioBenitez** [comment] 2018-11-21 05:00
Almost certainly a duplicate of #811 which itself has almost certainly been largely resolved upstream.

**Closed by SergioBenitez** 2018-11-21 05:00 UTC
