### ISSUE TITLE
the trait `rocket::request::FromFormValue<'_>` is not implemented for `models::chrono::NaiveDate`

### ISSUE THREAD

**Issue by luis-vmjr** [SergioBenitez/Rocket#602] opened 2018-04-10 21:29 UTC
### Versions

- **Rust:**
rustc 1.25.0-nightly

- **Rocket:**
0.3.8 (Apr 07, 2018)

- **Diesel:**
version = "1.1.0"

- **Database:**
PGsql 10.3
- **Operating System**
Windows 10 Fall creators update
### Feature Flags
chrono = { version = "0.4", features = ["serde"] }
- **diesel:**
diesel = { version = "1.1.0", features = ["postgres", "chrono", "large-tables" ] }

## Problem Description
I got a "NaiveDate" field at a diesel insertable struct that derives from rocket's request::FromForm  and the trait bound `models::chrono::NaiveDate: rocket::request::FromFormValue<'_>` is not being satisfied.

`#[derive(Insertable, Debug, FromForm)]`
`#[table_name="login"]`
`pub struct NewLogin {`
    `pub username: String,`
    `pub userpass: String,`
    `pub creation_date: Option<self::chrono::NaiveDate>,`     
`}`

### What is the expected output?
Successful compiling xD

### What is the actual output?
`error[E0277]: the trait bound `models::chrono::NaiveDate: rocket::request::FromFormValue<'_>` is not satisfied
   --> examples\freedu\src\models.rs:116:29
    |
116 | #[derive(Insertable, Debug, FromForm)]
    |                             ^^^^^^^^ the trait `rocket::request::FromFormValue<'_>` is not implemented for `models::chrono::NaiveDate`
    |
    = note: required because of the requirements on the impl of `rocket::request::FromFormValue<'_>` for `std::option::Option<models::chrono::NaiveDate>``

### Steps to reproduce
1. Create a struct with NaiveDate as a field type.
2. Use "LanientForm" from rocket.rs to fill it.
3. Add Derive(FromForm) to the struct;
4. Bug.

Full code source:
https://github.com/luis-vmjr/freedu/blob/master/src/models.rs

## Checklist

- [X ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by DJMcNab** [comment] 2018-04-11 15:36
But surely that leads to an orphaned impl, because he does not own NaiveDate or FromFormValue

I think that you could however create a wrapper, and use that in your Login; i.e:
```rust
struct NaiveDateForm(NaiveDate);

impl<'v> FromFormValue<'v> for NaiveDateForm {
    type Error = &'v RawStr;

    fn from_form_value(form_value: &'v RawStr) -> Result<NaiveDateForm, &'v RawStr> {
        // here, parse NaiveDate and return an instance of the wrapper
    }
}

impl Deref<NaiveDate> for NaiveDateForm{
    fn deref(self)->NaiveDate{
        self.0
    }
}
```

**Comment by SergioBenitez** [comment] 2018-04-13 17:34
We don't have built-in support for `chrono`, and `chrono` doesn't have built in support for Rocket. One of these would be required to allow this to work. That is, either `chrono` or `rocket` would need to implement `FromFormValue` for `NaiveDate`. We won't be doing that in Rocket's core, but perhaps you can ask `chrono` to do so under a `rocket` feature flag.

In general, this is an issue caused by coherence, as @DJMcNab alludes to. The workaround is exactly as @DJMcNab writes, though the `Deref` impl above needs to be slightly tweaked to compile.

I think this answers the question. As such, I'm closing the issue out. Feel free to comment if you feel your question hasn't been answered.

**Closed by SergioBenitez** 2018-04-13 17:34 UTC
Labels: question

**Comment by timando** [comment] 2021-09-16 05:33
Now that there's no longer a `contrib` crate, and `Uuid` has been added to core, does that change anything?

**Comment by NyxCode** [comment] 2021-11-08 14:02
I'm a bit suprised - Its super common in the rust ecosystem to gate an impl behind a feature.  
It's done almost everywhere for serde, and also for chrono in a *lot* of places. Why is rocket different?

**Comment by perseoGI** [comment] 2023-02-23 15:21
Any updates for this on Rocket v5?
