### ISSUE TITLE
Issues compiling examples

### ISSUE THREAD

**Issue by iamcharleschege** [SergioBenitez/Rocket#662] opened 2018-06-13 09:31 UTC
I am using Rocket 0.3.12 but seem to be running into issues while compiling the github examples. It seems as if there are some features that are deprecated but are still being used in the examples. I had to go through the API docs to rectify them. For example while compiling the github json example "catchers![not_found]"  does not exists but replacing it with "errors![not_found]" from the API docs it works. Another example is "rocket_contrib::{Json, JsonValue}" , here the compliler complains that "cannot find JsonValue in this scope" , from the API docs, "JsonValue" does not exists instead just using "Json" solves the problem.

Can you please update the examples at github because the examples on the official docs page are a bit shallow as they focus mostly on code snippets.

**Comment by jebrosen** [comment] 2018-06-13 11:20
Are you looking at the examples on the `master` branch, or for `0.3`? `master contains several breaking changes including the ones you mentioned.

**Comment by jlpettersson** [comment] 2018-06-15 17:09
How can I downgrade to 0.3?

If I change from 0.3.12 to 0.3 in my Cargo.toml and run `cargo build` it still builds with 0.3.12 that fails hard.

**Comment by jlpettersson** [comment] 2018-06-15 18:02
The missing piece is this command `rustup default nightly-2018-06-09`

**Comment by SergioBenitez** [comment] 2018-06-20 12:33
v0.3.13 works on the latest Rust nightly. The documentation already links to examples and code in the `v0.3` branch, with the exception of the `code` link. I think this is probably okay, though I have seen some confusion arise as a result. We should deal with this somehow, perhaps via a `README` in the example directory. Nonetheless, I don't think the issue is large enough to keep this open. Thus, closing for now.

**Closed by SergioBenitez** 2018-06-20 12:33 UTC
