### ISSUE TITLE
Does not build with msvc 2017

### ISSUE THREAD

**Issue by BarelyMalicious** [SergioBenitez/Rocket#711] opened 2018-07-18 14:56 UTC
I am on `rustc 1.29.0-nightly (1ecf6929d 2018-07-16)` with msvc 2017. Trying to compile rocket.rs/guide/getting-started, I get this huge error pastebin.com/8McnqiGX. Apparently it is a `ring` issue and was fixed over there https://github.com/briansmith/ring/pull/650 and is already released as a new version.

**Comment by BarelyMalicious** [comment] 2018-07-18 15:03
I see there have been issues reported regarding this here already but they are all closed and this is still not working, so I don't have any idea about anything now.

**Comment by dgriffen** [comment] 2018-07-18 15:36
Have you tried building the examples from the `v0.3` branch? IIRC that uses an older working version of ring.

**Comment by SergioBenitez** [comment] 2018-07-19 00:09
Duplicate of #457, #642, and whole bunch more. Please see the comments there.

**Closed by SergioBenitez** 2018-07-19 00:09 UTC
