### ISSUE TITLE
Failed compiling hello world example

### ISSUE THREAD

**Issue by iwxfer** [SergioBenitez/Rocket#1285] opened 2020-04-19 00:58 UTC
Followed instructions in https://rocket.rs/v0.4/guide/quickstart/

```
   Compiling indexmap v1.3.2
error: failed to run custom build command for `rocket_codegen v0.4.4 (C:\dev\Rocket\core\codegen)`

Caused by:
  process didn't exit successfully: `C:\dev\Rocket\target\debug\build\rocket_codegen-ae0c990e44d032a5\build-script-build` (exit code: 101)
--- stderr
Error: Rocket (codegen) requires a 'dev' or 'nightly' version of rustc.
Installed version: 1.42.0 (2020-03-09)
Minimum required:  1.33.0-nightly (2019-01-13)
See the getting started guide (https://rocket.rs/v0.5/guide/getting-started/) for more information.
thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', core\codegen\build.rs:29:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `pear_codegen v0.1.2`

Caused by:
  process didn't exit successfully: `C:\dev\Rocket\target\debug\build\pear_codegen-48ffb5255cbf3054\build-script-build` (exit code: 101)
--- stderr
Error: Pear requires a nightly or dev version of Rust.
Installed version is: 1.42.0 (2020-03-09). Minimum required: 1.31.0-nightly (2018-10-05).
thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', C:\Users\Fernando\.cargo\registry\src\github.com-1ecc6299db9ec823\pear_codegen-0.1.2\build.rs:31:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed


```

**Comment by tommket** [comment] 2020-04-19 09:59
I think that the line:
`Error: Rocket (codegen) requires a 'dev' or 'nightly' version of rustc.`
Summarizes it quite well. You need a nightly version of the Rust compiler (rustc).
See: [Rocket installing Rust](https://rocket.rs/v0.4/guide/getting-started/#installing-rust)

**Comment by tommket** [comment] 2020-04-19 10:03
There is also a tracking issue for compiling with stable Rust: #19

**Comment by jebrosen** [comment] 2020-04-19 16:50
Yes, you need a nightly compiler.

Closing as a duplicate of #940.

**Closed by jebrosen** 2020-04-19 16:50 UTC
