### ISSUE TITLE
Cookies.add_private needs a mut self

### ISSUE THREAD

**Issue by nathansamson** [SergioBenitez/Rocket#1095] opened 2019-08-16 18:51 UTC
## Bug Reports

Using rocket 0.4
https://api.rocket.rs/v0.4/rocket/http/enum.Cookies.html#method.get_private
Looking at the documentation of `Cookies.add_private`

`pub fn get_private(&mut self, name: &str) -> Option<Cookie<'static>>`

You see it needs a mutable self. Since I am merely reading this should not be needed and `&self` should suffice

The non private counterpart works without mutable.
`pub fn get(&self, name: &str) -> Option<&Cookie<'static>>`

If there is an underlying reason with the `get_private` method needs to modify the internal struct, it should be explained in the docs as not to cause confusion.

Also the docs seem to be wrong if mutable is really needed snippet from (https://rocket.rs/v0.4/guide/requests/#private-cookies)

> /// Retrieve the user's ID, if any.
#[get("/user_id")]
fn user_id(cookies: Cookies) -> Option<String> {
    cookies.get_private("user_id")
        .map(|cookie| format!("User ID: {}", cookie.value()))
}

**Comment by joeyjoejoejr** [comment] 2019-08-16 20:42
The private cookie jar wraps a regular one.  It is used mutably here: https://github.com/SergioBenitez/cookie-rs/blob/master/src/secure/private.rs#L112 and I don't think the docs are wrong because here https://github.com/SergioBenitez/Rocket/blob/3e4f8453ce4e563e1791a4fe3d5a8eafdfd17a6e/core/http/src/cookies.rs#L131, a jarred variant of the Cookies enum already contains a mutable reference.

**Comment by nathansamson** [comment] 2019-08-16 20:55
In your first link you are referring to the `add` method. It stands to reason that that needs to be mutable.

My problem is with the `get` method which in your `CookieJar` is not mutable https://github.com/SergioBenitez/cookie-rs/blob/master/src/secure/private.rs#L80


Also if you look at https://github.com/SergioBenitez/Rocket/blob/3e4f8453ce4e563e1791a4fe3d5a8eafdfd17a6e/core/http/src/cookies.rs#L273

You see the example being "right" here and explicitely in the example it says `fn handler(mut cookies: Cookies) {` which also corresponds with the signature of the method ` pub fn get_private(&mut self, name: &str) -> Option<Cookie<'static>>`
Note that Cookies here is mutable.

BUT if you look in the guides. https://rocket.rs/v0.4/guide/requests/#private-cookies
You see an example like. Note that in this handler Cookies is not mut, but `get_private` is called. I believe this code will not compile.

> `fn user_id(cookies: Cookies) -> Option<String> {
>     cookies.get_private("user_id")
>         .map(|cookie| format!("User ID: {}", cookie.value()))
> }`


So unless I am misunderstanding something, the guide seems wrong?

**Comment by joeyjoejoejr** [comment] 2019-08-16 21:15
Ok.  Sorry I jumped a couple of step here.

On you first question:

First look here
https://github.com/SergioBenitez/Rocket/blob/3e4f8453ce4e563e1791a4fe3d5a8eafdfd17a6e/core/http/src/cookies.rs#L293

Then follow that the the `private` function here https://github.com/SergioBenitez/cookie-rs/blob/master/src/jar.rs

**Comment by joeyjoejoejr** [comment] 2019-08-16 21:21
Ok.  Sorry I jumped a couple of step here.

On you first question:

First look here
https://github.com/SergioBenitez/Rocket/blob/3e4f8453ce4e563e1791a4fe3d5a8eafdfd17a6e/core/http/src/cookies.rs#L293

Then follow that the the `private` function here https://github.com/SergioBenitez/cookie-rs/blob/master/src/jar.rs#L387

You can see that `private` function takes a mutable reference and stores it internally as `parent`.

On you second question:
The guide is now wrong.  You can set it up and compile it yourself if you don't believe me. 😄 

The `Cookie` type that is passed in already contains a mutable ref cell.  So you don't have to explicitly take it mutably in your handler function.  Checkout out the docs for `RefMut` https://doc.rust-lang.org/std/cell/struct.RefMut.html

Also, maybe someone with more experience can answer your question a little more clearly.  I'm pretty new to this codebase.

**Comment by nathansamson** [comment] 2019-08-16 21:29
I think I tried to compile it and it failed, hence why I made this bug report :)

But Ill try it again tomorrow, very well possible that I was doing something wrong somewhere else and misinterpreted the compiler error (pretty new to rocket and rust)

**Comment by joeyjoejoejr** [comment] 2019-08-16 21:38
Oh.  I take it back.  I'm not actually using the request guard in any of my code. https://github.com/SergioBenitez/Rocket/blob/3e4f8453ce4e563e1791a4fe3d5a8eafdfd17a6e/core/lib/tests/local_request_private_cookie-issue-368.rs#L13

You may be right.

**Comment by jebrosen** [comment] 2019-08-16 23:17
I think this is a partial duplicate of #911. But it does look like the code in the guide needs to be fixed.

**Comment by nathansamson** [comment] 2019-08-17 15:12
> 
> 
> I think this is a partial duplicate of #911. But it does look like the code in the guide needs to be fixed.

Ok, FYI I searched for bugs with `get_private` but github did not turn up that one. `cookies.get_private` finds it though. Not really intuitive from github search :)

I had a quick look at the code, and I think having it non mutable would be too much work with the current architecture (it creates a 

> `pub struct PrivateJar<'a> {
    parent: &'a mut CookieJar,
    key: [u8; KEY_LEN]
}`

so unless I am mistaken and a `PrivateJarReadOnly` with a non mut CookieJar is created it can be done, but that would mean lots of code duplication I believe.


Marking a Cookies as mut in my handler is not really an issue (although it would mark as a usefull indication it only reads, and does not do writes)

**Comment by nathansamson** [comment] 2019-08-17 15:15
Just noticing I messed up the title and mention `add_private` while I meant `get_private` which might explain the original confusion with  joeyjoejoejr 😊

**Closed** 2019-11-16 21:24 UTC
Labels: docs
