### ISSUE TITLE
Responder not implemented when derived

### ISSUE THREAD

**Issue by marhag87** [SergioBenitez/Rocket#856] opened 2018-12-11 08:02 UTC
1. The version of Rocket you're using. Ensure it's the latest, if possible.
0.4.0

  2. The operating system (distribution and version) where the issue occurs.
Ubuntu 18.04.1 LTS

  3. A brief description of the bug that includes:
I'm trying to use derive(Responder) from the new version to create a custom error but can't seem to use it in a Result. When I use it by itself it works.

  4. How you uncovered the bug. Short, reproducible tests are especially useful.
Here is a small program that shows my intention. Curling /fail gives me 403 with an error message as expected.
```
#![feature(proc_macro_hygiene, decl_macro)]
#[macro_use] extern crate rocket;

#[derive(Responder)]
enum MyError {
    #[response(status = 403)]
    Unauthorized(String),
}

#[get("/fail")]
fn fail() -> MyError {
    MyError::Unauthorized("Error".to_string())
}

#[get("/success")]
fn success() -> String {
    "OK".to_string()
}

//#[get("/test")]
//fn test() -> Result<String, MyError> {
//    //Ok("OK".to_string())
//    Err(MyError::Unauthorized("Error".to_string()))
//}

fn main() {
    rocket::ignite().mount("/", routes![success, fail]).launch();
}
```
If I try to uncomment the test endpoint and compile I get the following error message:
```
error[E0277]: the trait bound 'std::result::Result<std::string::String, MyError>: rocket::response::Responder<'_>' is not satisfied
  --> src/main.rs:20:1
   |
20 | #[get("/test")]
   | ^^^^^^^^^^^^^^^ the trait 'rocket::response::Responder<'_>' is not implemented for 'std::result::Result<std::string::String, MyError>'
   |
   = help: the following implementations were found:
             <std::result::Result<R, E> as rocket::response::Responder<'r>>
             <std::result::Result<R, E> as rocket::response::Responder<'r>>
   = note: required by 'rocket::handler::<impl rocket::Outcome<rocket::Response<'r>, rocket::http::Status, rocket::Data>>::from'
```

  5. Ideas, if any, about what Rocket is doing incorrectly.

**Comment by jebrosen** [comment] 2018-12-11 16:11
The problem is actually that `MyError` does not implement `Debug`; it's along the lines of `impl<T: Responder, E: Debug + Responder> Responder for Result<T, E>`.

**Comment by SergioBenitez** [comment] 2018-12-11 23:31
As @jebrosen alludes to, adding `Debug` to the `derive` on `MyError` should resolve your issue. I'm closing this out because of this. If that doesn't resolve your issue, please let us know and we'll revisit this.

**Closed by SergioBenitez** 2018-12-11 23:31 UTC

**Comment by marhag87** [comment] 2018-12-12 06:31
That does indeed solve it. Thanks!

**Comment by cazgp** [comment] 2019-11-01 14:17
Is there a way to change the error message for this? It took a while to hunt down that this was the cause of the issue. My rust-fu isn't good enough to know the answer.

**Comment by jebrosen** [comment] 2019-11-01 14:47
I can't think of any way to make the error message better (short of fixing the bug in rustc itself). However, commit 2537a11 in `master` removes the use of the `specialization` feature, which is part of the reason the error message is unhelpful.

In the next release we will only have `Result<T: Responder, E: Responder>`; for the current behavior of types that implement `Debug` you would use `Result<SuccessType, rocket::response::Debug<ErrorType>>`.
