### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by silvioprog** [SergioBenitez/Rocket#1879] opened 2021-09-01 00:32 UTC
Some links (e.g "crates docs") are broken at: https://github.com/SergioBenitez/Rocket/tree/master/contrib/db_pools

**Comment by jebrosen** [comment] 2021-09-01 00:41
This is a duplicate of #1783. This kind of thing seems to be happening a lot recently; is there a particular reason you are referring to the GitHub repository instead of to the website and API documentation which cover published releases?

**Closed by jebrosen** 2021-09-01 00:41 UTC
Labels: triage

**Comment by silvioprog** [comment] 2021-09-01 00:57
The link points to a missing page at website, https://api.rocket.rs/v0.5-rc/rocket_db_pools. It returns 404.

**Comment by jebrosen** [comment] 2021-09-01 01:06
That is more or less expected: the `master` branch includes unreleased content, including crates and website text. My question was more about, how did you find your way to the code and documentation in the `master` branch? On Rocket's [website](https://rocket.rs/), nearly all of the links point specifically to `v0.5-rc`.

**Comment by silvioprog** [comment] 2021-09-01 01:13
> That is more or less expected: the master branch includes unreleased content, including crates and website text.

So this explains the problem.

> My question was more about, how did you find your way to the code and documentation in the master branch?

Oh, my bad, I found it just by navigating in the examples and checking for broken links, to avoid them in the next released docs. 😅

> On Rocket's website, nearly all of the links point specifically to v0.5-rc.

Hm... the broken link also points to `v0.5-rc`. 🤔 But since it is more or less expected, let's wait the next release. (I'm looking forward to it hehe)
