### ISSUE TITLE
Mounting "/" routes to a sub-path removes trailing slash from route

### ISSUE THREAD

**Issue by stefan0xC** [SergioBenitez/Rocket#2533] opened 2023-05-02 18:56 UTC
**Description**

Mounting a `#[get("/")]` route to a sub-path removes the trailing slash, which leads to unexpected behavior.

**To Reproduce**

Create a `src/main.rs` : 
```rust
#[macro_use] extern crate rocket;

#[get("/")]
fn index() -> &'static str { 
    "Hello, world!"
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/test/", routes![index])
}
```

and `Cargo.toml`

```toml
[package]
name = "rocket-example"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { git = 'https://github.com/SergioBenitez/Rocket', rev = '9b0564ed27f90686b333337d9f6ed76484a84b27' }
```

Run `cargo run` and check difference of calling `curl http://127.0.0.1:8000/test` (which works) and `curl http://127.0.0.1:8000/test/` (404).

```
   Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/rocket-example`
🔧 Configured for debug.
   >> address: 127.0.0.1
   >> port: 8000
   >> workers: 12
   >> max blocking threads: 512
   >> ident: Rocket
   >> IP header: X-Real-IP
   >> limits: bytes = 8KiB, data-form = 2MiB, file = 1MiB, form = 32KiB, json = 1MiB, msgpack = 1MiB, string = 8KiB
   >> temp dir: /tmp
   >> http/2: true
   >> keep-alive: 5s
   >> tls: disabled
   >> shutdown: ctrlc = true, force = true, signals = [SIGTERM], grace = 2s, mercy = 3s
   >> log level: normal
   >> cli colors: true
📬 Routes:
   >> (index) GET /test/
📡 Fairings:
   >> Shield (liftoff, response, singleton)
🛡️ Shield:
   >> X-Frame-Options: SAMEORIGIN
   >> Permissions-Policy: interest-cohort=()
   >> X-Content-Type-Options: nosniff
🚀 Rocket has launched from http://127.0.0.1:8000
GET /test/:
   >> No matching routes for GET /test/.
   >> No 404 catcher registered. Using Rocket default.
   >> Response succeeded.
GET /test:
   >> Matched: (index) GET /test/
   >> Outcome: Success
   >> Response succeeded.
```

**Expected Behavior**

After 51ed332127df2737a7d1c1a22a1e13379ea5f6d5 I expected the resource to be available only under the route `/test/` (which is also what the logs say where the route lives) but it appears the loaded route is `/test`.

**Environment:**

 - OS Distribution and Kernel: Arch Linux 6.2.12-arch1-1
 - Rocket Version: master@9b0564ed27f90686b333337d9f6ed76484a84b27

**Additional Context**

We ran into this issue in [vaultwarden](https://github.com/dani-garcia/vaultwarden) after we updated our Rocket dependency to 9b0564ed27f90686b333337d9f6ed76484a84b27  - 
Due to our custom logging the reported routes https://github.com/dani-garcia/vaultwarden/discussions/3495#discussioncomment-5783685  are the actual loaded routes.

**Comment by SergioBenitez** [comment] 2023-05-02 22:27
Looking into this now.

**Comment by SergioBenitez** [comment] 2023-05-02 22:52
Confirmed as a bug. Working on a fix now.

**Comment by SergioBenitez** [comment] 2023-05-03 01:00
After a closer look, this is not quite a bug, but it is really unfortunate.

Previously, when we wrote `mount("/foo", routes![index])`, where `index.uri = "/"`, Rocket would route requests to `/foo` to `index`. This is inconsistent with the changes in https://github.com/SergioBenitez/Rocket/commit/51ed332127df2737a7d1c1a22a1e13379ea5f6d5, where the expected behavior would be for this combination of mount point (`/foo`) and route URI (`/`) to accept requests to `/foo/` and _not_ `/foo`. But this would result in breaking applications that expected the previous behavior.

I had hoped to "protect" against breaking applications that expect such a mount point/route URI combination to react as before by specifically checking for this case and "fixing" it automatically:

https://github.com/SergioBenitez/Rocket/blob/6ab85b6643289016be5e7905ad5c1fa44e9ce2d6/core/lib/src/route/uri.rs#L123-L130

But this results in the issue laid out here, where we strip the trailing slash when it's not intended.

The ambiguity is present only when the route URI is `/` and the mount point is non-empty, as in this example. The question becomes whether the effective route URI should be `/base/` or `/base`:
  * `mount("/base", "/")` => `/base` OR `/base/`

A related concern, and perhaps a way to resolve this issue, is whether a trailing path in the mount point is meaningful. Up to and including now, a trailing slash in a mount point has no meaning. That is:

 * ∀ B, R. `mount(B, R)` `==` `mount(B/, R)`

But one way to remove the need to choose between  `mount("/base", "/")` resolving as either `/base` OR `/base/` is to say that it resolves to the former always, and that resolving to the latter would require `mount("/base/", "/')`. This has the advantage of probably keeping existing code working. I say _probably_ because we've  still changed the meaning of `mount("/base/", "/")`, which would previously also resolve to `/base`. This has the disadvantages that it 1) introduces a special case, 2) is probably pretty confusing, 3) isn't consistent with the intention behind https://github.com/SergioBenitez/Rocket/commit/51ed332127df2737a7d1c1a22a1e13379ea5f6d5, and 4) doesn't fix all of the cases.

So I'm inclined to say that we simply bite the bullet fully and commit to the breaking change. That is, `mount("/base", "/")` resolves to `/base/` _always_, and we continue to provide that ∀ B, R. `mount(B, R)` `==` `mount(B/, R)`.

**Comment by SergioBenitez** [comment] 2023-05-03 18:41
After further consideration, perhaps we _should_ distinguish between mount points of `/foo` and `/foo/`.

Consider a resource `users` using a typical REST architecture. One such API might look like:

```
POST /users            - add new user
GET  /users/<id>       - get a user with ID `id`
```

Writing such an API in Rocket today looks like:

```rust
mod users {
    #[post("/")] fn add() -> Result<User> { .. }
    #[get("/<id>")] fn get() -> User { .. }
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/users", routes![users::add, users::get])
}
```

But with the proposed changes in my comment above, the effective routes would be:

```diff
- POST /users            - add new user
+ POST /users/           - add new user
GET  /users/<id>       - get a user with ID `id`
```

Which doesn't match the desired API. To get the desired behavior, we would need to declare the `add` route as having a URI of `/users`, which breaks the desired modularity. Of course, there's nothing wrong with `POST /users/`, but it seems odd that Rocket would make it impossible to have `POST /users` without succumbing to writing more code and making the program harder to modularize. By a similar token, it seems odd to disallow `POST /users/`.

So it seems we _do_ want to give the ultimate choice to the user, and one simple way to do that is to use the mount point as the distinguisher. While I do believe it will cause some confusion, hopefully we can attenuate that with better docs, precise logging, and obvious semantics.

**Comment by tessus** [comment] 2023-05-03 19:06
The problem is that there is no standard for REST or API specs.

However, most API devs came to the conclusion that `/path` points to a resource and `/path/` to a resource group. (But I have also seen different implementations.)

But it should be clear that `/path` and `/path/` or 2 different URIs. Rocket should make it easy for the programmer to point:

- `/path` to function A
- `/path/` to function B
- `/path` and `/path/` to the same function C

Does this make sense or am I way off here?

**Comment by SergioBenitez** [comment] 2023-05-03 19:11
No, you're totally on point, and this is exactly what I'm alluding to. As it stands, as of https://github.com/SergioBenitez/Rocket/commit/51ed332127df2737a7d1c1a22a1e13379ea5f6d5 Rocket properly differentiates between URIs with trailing slashes and not and allows you to declare routes that match one or the other. The issue here is what effect mount points should have on the effective URI of routes with a path of `/`. My conclusion above is that a mount point of `/foo/` results in an effective URI of `/foo/` and a mount point of `/foo` an effective URI of `/foo`. Here's a table of what I'm proposing:

| mount point | route URI  | effective URI |
|-------------|------------|---------------|
| `/`         | `/`        | `/`           |
| `/`         | `/foo`     | `/foo`        |
| `/`         | `/foo/bar` | `/foo/bar`    |
| `/foo`      | `/`     | `/foo`    |
| `/foo`      | `/bar`     | `/foo/bar`    |
| `/foo`      | `/?baz`     | `/foo?baz`    |
| `/foo`      | `/bar?baz`     | `/foo/bar?baz`    |
| `/foo/`      | `/`     | `/foo/`    |
| `/foo/`      | `/bar`     | `/foo/bar`    |
| `/foo/`      | `/?baz`     | `/foo/?baz`    |
| `/foo/`      | `/bar?baz`     | `/foo/bar?baz`    |

Does this make sense and sound reasonable?

**Comment by tessus** [comment] 2023-05-03 19:16
Yes, for me this makes total sense, but I am not the OP. @stefan0xC what do you think?

**Comment by SergioBenitez** [comment] 2023-05-03 19:17
> But it should be clear that `/path` and `/path/` are 2 different URIs. Rocket should make it easy for the programmer to point:
> 
> * `/path` to function A
> * `/path/` to function B
> * `/path` and `/path/` to the same function C

There are two ways to do this, with the proposal above.

The first is by just defining routes that correspond to the paths:

```rust
#[get("/path")] fn a() {}
#[get("/path/")] fn b() {}

#[get("/path")] fn a() {}
#[get("/path/")] fn b() { a() }
```

The second would be via mounting:

```rust
#[get("/")] fn a() {}
#[get("/")] fn b() {}
#[get("/")] fn c() {}

rocket::build()
    .mount("/path", routes![a, c])
    .mount("/path/", routes![b, c])
```

**Comment by tessus** [comment] 2023-05-03 19:27
I think there should also be rules for edge cases:

mount point | route URI | effective URI
-- | -- | --
/foo  |     | ???
/foo  | bar | ???
/foo/ |     | ???
/foo/ | bar | ???

That ia unless the route URI always has to start with a `/` or Rocket automatically prefixes any route that does not start with a `/` with a `/`.

**Comment by SergioBenitez** [comment] 2023-05-03 19:35
Route URIs _must_ be valid origin URIs, which means they must start with a `/`.

**Comment by tessus** [comment] 2023-05-03 23:03
Ah, I missed 2 cases for the above table.

mount point | route URI | effective URI
-- | -- | --
/ | /foo/      | /foo/
/ | /foo/bar/  | /foo/bar/

This is correct, right?

**Comment by SergioBenitez** [comment] 2023-05-03 23:20
> This is correct, right?

Yep!

**Closed** 2023-05-04 03:13 UTC
Labels: deficiency
