### ISSUE TITLE
No output in a container

### ISSUE THREAD

**Issue by mladedav** [SergioBenitez/Rocket#2174] opened 2022-05-11 10:03 UTC
**Description**

I build a Rocket app in Docker but when I run it it seemingly hangs and produces no output. I have verified though that I can connect to it. If I exec into the container and run `cargo build` the app starts producing output after the restart.

**To Reproduce**

I've prepared a repo here: https://github.com/mladedav/rocket-docker
You can run `docker build -t rocket-build . && docker run -it --rm rocket-build /bin/bash`
and inside the container `./target/release/rocket-demo` and there is no output. (You can additionally apt install curl, start the app in background and verify that it serves content). If you run `cargo build -r && ./target/release/rocket-demo` output is produced as usual.

**Expected Behavior**

To see logs in the container.

**Environment:**

 - OS Distribution and Kernel: Host system is Windows 10; Docker image is rust:1.60 which is Debian bullseye
 - Rocket Version: 0.5.0-rc.1 and 0.5.0-rc.2

**Comment by SergioBenitez** [comment] 2022-05-11 10:39
See #1469, #1478. It doesn't look like you're setting the address to listen on to something docked lets you access from the outside world, i.e., `0.0.0.0`. Closing as this is almost certainly not a bug. Please comment if proper configuration doesn't resolve your issue.

**Closed** 2022-05-11 10:39 UTC
Labels: triage

**Comment by mladedav** [comment] 2022-05-11 12:22
You were right that there was no output because of bad configuration. I did not realize that release builds log only criticals. However, it seems that the compiled binary inside the container is ignoring the `rocket.toml` file next to it unless `ROCKET_CONFIG` is specified. It works as specified by the docs locally but for some reason not inside of a container. Environment variable overrides work.

**Comment by SergioBenitez** [comment] 2022-05-11 13:00
That seems unlikely as well. See #1811.

**Comment by mladedav** [comment] 2022-05-11 13:14
You're right again. Locally I used Windows which ignores case for file names. I named the config file `rocket.toml` instead of `Rocket.toml` and when it was supposed to run on Debian, the config file got ignored.

Sorry for wasting your time.
