### ISSUE TITLE
Websockets on Rocket?

### ISSUE THREAD

**Issue by catroot** [SergioBenitez/Rocket#448] opened 2017-10-03 12:47 UTC
Hello!
Is there possible to upgrade http connection with Rocket to handle websockets?
Similar to routings like
#[get("/")]
but with
#[ws("/")]

This will be very handy

**Comment by belst** [comment] 2017-10-03 12:55
see #33

**Comment by catroot** [comment] 2017-10-03 13:12
Thanks for pointing me. Polling and LongPolling is another feature.
My vote is for WS support out of the box.

**Comment by SergioBenitez** [comment] 2017-10-03 15:12
Duplicate of #90.

**Closed** 2017-10-03 15:11 UTC
Labels: duplicate
