### ISSUE TITLE
Base url when behind reverse proxy

### ISSUE THREAD

**Issue by agraven** [SergioBenitez/Rocket#1208] opened 2020-01-21 09:04 UTC
Rocket can't be used when behind a reverse proxy that sets a base url to something other than the domain's root, i.e. `www.site.com/app-name/`, as redirects break because what should be `/app-name/api-point` turns into just `/api-point`.

This makes rocket web apps frustrating to use when there is a large amount of services being run at a particular domain, as each rocket webapp has to be served at its own subdomain.

Some configuration option that would account this would make rocket usable in such an environment. It would presumably have to be exposed so templates and such could access it.

**Comment by jebrosen** [comment] 2020-01-25 17:16
I believe this is a duplicate of #828, where a few workaround ideas have been proposed but nothing very concrete. The TL;DR is that it's useful and desirable, but it's hard to implement and test primarily because it would require new global state and/or significant new APIs.

**Closed by jebrosen** 2020-01-25 17:16 UTC
