### ISSUE TITLE
impl Responder for Box<T> where T: Responder

### ISSUE THREAD

**Issue by am0d** [SergioBenitez/Rocket#568] opened 2018-02-21 01:50 UTC
## Feature Requests
Please consider implementing `Responder` for  `Box<T> where T: Responder`.
This would allow a function to easily return multiple types of Response.
I've tried doing this with a function that returns `impl Responder`, but that gives me an error if I try to return multiple types that each implement `Responder`.
I'm thinking of a function that would potentially return e.g. a Template in one case, and maybe a redirect or a flash in another case.
I've kind of managed to hack around this in one case by returning `Result<Flash<Redirect>, Template>`, but that feels wrong because there are 2 error conditions - one error case redirects (as does the success case), while the other error case returns a template.
You may argue that this is the wrong way of doing it, but having the ability to do this would really help me reuse more of the code that I've already written.
I've not found any way to implement this or something similar (e.g. a wrapper type) that doesn't have too much code overhead, although if someone has an alternative approach here I'd be willing to look at that.

Below is the error message that I currently get when I define a function to return `Box<Response>`:
```
error[E0277]: the trait bound `std::boxed::Box<rocket::response::Responder<'static>>: rocket::response::Responder<'_>` is not satisfied
  --> src/controllers/period.rs:67:1
   |
67 | #[post("/<id>/edit", data = "<period_form>")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `rocket::response::Responder<'_>` is not implemented for `std::boxed::Box<rocket::response::Responder<'static>>`
   |
   = note: required by `rocket::handler::<impl rocket::Outcome<rocket::Response<'r>, rocket::http::Status, rocket::Data>>::from`
```

**Comment by SergioBenitez** [comment] 2018-02-21 03:23
You can already use a `Result` for this, and we might imagine Rocket having an `Either` type (or using the existing one) to alleviate the implications of returning a `Result`.

For more than two possible result types, Rocket advocates for using a custom enum. In `0.4`, you'll be able to derive `Responder`, making this even easier:

```rust
#[derive(Responder)]
enum MyResponse {
    A(Template),
    B(Redirect),
    C(Error)
}

I am unsure if we should implement this (hence my accept/not accept). A `Box<Responder>` has no meaning whatsoever; it can be anything. Rocket advocates for types having meaning. This is why returning a `Response` is frowned upon and may, in fact, be made impossible in future versions of Rocket. I fear that making this possible will simultaneously making Rocket code harder to follow and lead to users `Box`ing things unnecessarily.

**Comment by weiwei-lin** [comment] 2018-02-22 09:15
> You can already use a Result for this, and we might imagine Rocket having an Either type (or using the existing one) to alleviate the implications of returning a Result.

Could you demonstrate that how we can return multiple error types with Result?



> For more than two possible result types, Rocket advocates for using a custom enum. In 0.4, you'll be able to derive Responder, making this even easier:

This is really cool. Looking forward to 0.4 release.

**Comment by SergioBenitez** [comment] 2018-02-23 08:12
@weiwei-lin Nest them: `Result<T, Result<E1, E2>>`. You can do this as many times as you want: `Result<T, Result<E1, Result<E2, Result<E3, E4>>>>`.

**Comment by am0d** [comment] 2018-04-16 19:36
I ended up using a custom enum for my implementation, with helper functions that define the purpose of what I'm returning rather than the actual type of what I'm returning, which I've found works fairly well.
See my implementation [here](https://github.com/am0d/rocket-test/blob/master/src/util/response.rs) and a sample controller using 2 different return types [here](https://github.com/am0d/rocket-test/blob/master/src/controllers/period.rs#L78).

**Comment by SergioBenitez** [comment] 2018-04-22 00:04
Closing in favor of #590.

**Closed by SergioBenitez** 2018-04-22 00:04 UTC
Labels: request

**Comment by SergioBenitez** [comment] 2018-04-22 07:42
There is nothing to fix here; there is no functionality that Rocket is preventing here. The argument to make is one of convenience, which you've stated. My counter-argument is that if we approach #590 the correct way, then solutions are just as convenient while simultaneously not having the same readability, performance, and safety drawbacks I mention in my previous comment.

What is your real-world use-case in which you feel a custom `enum` won't suffice? All of the previous cases you've mentioned can be contained in a single `enum`, though it's unclear what you're actually trying to achieve here. But as an example, if you want to be able to return a `Template` or `Redirect` on failure with a `400`, as well as `Template`, `String`, or `Json` on success, you can have the following enum:

```rust
#[derive(Responder)]
enum Response {
    #[response(header = "<1>")]
    Page(Template, Status),
    Static(String),
    Schema(Json),
    Unknown(Redirect),
}

#[get("/")]
fn example() -> Response { }
```

This is probably pretty unlikely in practice. At most, I've had three different variants that I've needed to capture in a single handler.

**Comment by DanielJoyce** [comment] 2021-03-09 17:33
Why I should have to implement wrapper types for responses, when supporting existing Boxed versions of Errors, Status, etc would suffice? 

Code written is code you have to support, whereas simply supporting Result<Box<Responder>,Box<Error>> would handle the vast majority of use cases without requiring new types or having to expand them all the time as you write code.

Warp supports boxed errors for example, and I don't have to add extra code just to wrap them to make things happy when a endpoint might return multiple error types.

**Comment by DanielJoyce** [comment] 2021-03-09 17:43
Fox example, in your examople, Json is generic and the Responder macro doesn't support it.
```
#[derive(Responder)]
enum Success {
    Page(Template),
    Static(String),
    Schema(Json),
}
```

**Comment by DanielJoyce** [comment] 2021-03-09 17:49
#[derive(Responder)]
enum Success {
    Page(Template),
    Static(String),
    Schema(Json),
}

Doesn't work, as Json is generic, and Responder macro doesn't support generics

**Comment by SergioBenitez** [comment] 2021-03-10 01:52
> Why I should have to implement wrapper types for responses, when supporting existing Boxed versions of Errors, Status, etc would suffice?

Instead of thinking of these as "wrapper" types, think of them as _distinct_ response types, as they are, and thus nominally and distinctly convey information about the response. The crux is that a `Box<Responder>` says _nothing_ about the underlying type or response - indeed, this is type erasure. By contrast, Rocket's philosophy is that types are _meaningful_ syntactically and semantically. You should be able to read a route handler's signature and learn something considerable about the route:

```rust
#[get("/<path..>")]
fn foo(path: PathBuf) -> Option<Json<MyType>>;
```

This route takes a path - as long as it's valid for use as a `PathBuf` - and maybe returns the JSON representation of `MyType`. We've gleamed a lot about this route just from the signature! Contrast this with type erasure everywhere:

```rust
#[get("/<path..>")]
fn foo(path: Box<dyn FromParam>) -> Box<dyn Responder>;
```

We still know that this route matches everything at `/<path..>`, but now we know nothing about _which_ paths are valid or what kind of response we might produce. We've lost almost all of the information we were previously able to gleam.

Consequentially, I do not see Rocket ever supporting fully type-erased responses.

> Warp supports boxed errors for example, and I don't have to add extra code just to wrap them to make things happy when a endpoint might return multiple error types.

The [`Debug<E>`](https://api.rocket.rs/master/rocket/response/struct.Debug.html) type implements `Responder` for all `E: Debug`. You _can_ return a `Result<T, Debug<Box<dyn Debug>>>`, for example. The `Debug` type makes it clear that the response is doing "nothing" but being debugged, so we lose nothing by allowing type erasure here.

> The Responder Macro for instance doesn't handle generics. NotFound and its siblings are structs, they aren't a enum, so you need to wrap them individually.

There's nothing preventing the `Responder` derive from being able to handle type generics but implementation effort. I'd be happy to review a PR that adds type generic support, if you'd like to contribute! Note that the derive _does_ support lifetime generics.

**Comment by DanielJoyce** [comment] 2021-03-10 17:19
The problem is say I have a endpooint that might return Json or a status ( Perfectly valid ).

I don't think most developers care about the return type of a function whose value is not really consumed by other functions, but simply goes out over the internet. If it is returning `Result<MySuccess, MyError>` it's still not obvious what actual values that endpoint is returning without reading the code.

the Responder macro only supports one liftetime

``` rust
#[derive(Responder)]
pub enum ApiSuccess {
    Json(JsonValue),  # First bit of fun, responder macro doesn't support generics
    // Json(Json<V>),
    NotFound(NotFound),  # Each existing status I need to expose, I now need to wrap AGAIN
    Unauthorized(Unauthorized),
    Status((Status,String)) # Would be a handy shortcut, but macro can't implement, has two lifetimes, Responder! only supports on.
}
```

Now given how common it is for a endpoint to return a Status or perhaps a value, out of the box, I already need to do this wrapping.

This wouldn't be so painful if the existing types all were part of a overarching status enum, but they aren't. And I can understand reasons for that.

If I do what is suggested here:

```
#[derive(Responder)]
enum Error {
    #[response(status = 500, content_type = "json")]
    A(String),
    #[response(status = 404)]
    B(NamedFile, ContentType),
}
```

I now have multiple impls of 404. Some endpoints or fairings might return status::NotFound while others return Error::B, and I need to now keep them in sync.

**Comment by SergioBenitez** [comment] 2021-03-10 22:11
> ``` rust
> 
> #[derive(Responder)]
> 
> pub enum ApiSuccess {
> 
>     Json(JsonValue),  # First bit of fun, responder macro doesn't support generics
> 
>     // Json(Json<V>),
> 
>     NotFound(NotFound),  # Each existing status I need to expose, I now need to wrap AGAIN
> 
>     Unauthorized(Unauthorized),
> 
>     Status((Status,String)) # Would be a handy shortcut, but macro can't implement, has two lifetimes, Responder! only supports on.
> 
> }
> 
> ```

Your structure has no lifetimes. What's more, a response with more that one lifetime doesn't have sense in Rocket: the response either borrows from the request or it doesn't. Any other lifetime won't outlive request handling, and any shorter lifetime can be coerced to the request's lifetime.
