### ISSUE TITLE
"Lenient" parsing of get query params

### ISSUE THREAD

**Issue by Johnlon** [SergioBenitez/Rocket#620] opened 2018-05-03 00:43 UTC
If there are additional query params of get requests then I would like the option of ignoring them.
However are present any unexpected params cause a 404.

By contrast on post request I can use LenientForm to avoid this situation.

How can I achieve lenience on get request query parameter processing.

**Comment by maxdeviant** [comment] 2018-05-03 04:40
See the [Query Strings](https://rocket.rs/guide/requests/#query-strings) section of the docs, it provides an example of how to do this.

**Comment by Johnlon** [comment] 2018-05-03 09:44
Hi I was unable to find the relevant example.

So my get query accepts a and b
But I'm calling with a b c and I want c ignored

**Comment by maxdeviant** [comment] 2018-05-03 13:46
From the docs:

> Rocket will parse the query string into the Task structure automatically by matching the structure field names to the query parameters. If the parse fails, the request is forwarded to the next matching route. Parse failures can be captured on a per-field or per-form basis.
> To catch failures on a per-field basis, use a type of Option or Result for the given field:

So I believe something like this would do what you want:

```rust
#[derive(FromForm)]
struct Params {
    a: u8,
    b: u8,
    c: Option<u8>
}
```

**Comment by Johnlon** [comment] 2018-05-03 14:00
Hi thanks

I can see you added "c" to the structure but I don't want "c" in my code
base.
I just want superfluous arguments ignored entirely.

**Comment by SergioBenitez** [comment] 2018-05-05 08:01
This is effectively a duplicate of #628. In short: there is a query string handling reform coming soon (#608) that makes what you're trying to do possible. Let's track this issue there.

**Closed by SergioBenitez** 2018-05-05 08:01 UTC
