### ISSUE TITLE
Is there any function/method to shutdown a Rocket-based server? (could not find rocket::shutdown::ShutdownHandle)

### ISSUE THREAD

**Issue by silvioprog** [SergioBenitez/Rocket#1246] opened 2020-02-28 15:07 UTC
* Rocket 0.4.2
* Cargo 1.43.0-nightly
* Rustup 1.21.1

Hi.

I have been trying to use Rocket in a small service on Windows (code available [here](https://github.com/risoflora/fiscalidade_server/blob/master/src/service_windows.rs#L59)), but I found a problem: how to shutdown the server when the service is stopped? Then I found this [official example](https://api.rocket.rs/async/rocket/shutdown/struct.ShutdownHandle.html), but when I try to build my project using it:

```
   Compiling fiscalidade_server v0.7.0 (C:\dev\git\fiscalidade_server)
error[E0432]: unresolved import `rocket::shutdown`
 --> src\service_windows.rs:4:13
  |
4 | use rocket::shutdown::ShutdownHandle;
  |             ^^^^^^^^ could not find `shutdown` in `rocket`

error: aborting due to previous error
```

So, is there any function/method to shutdown a Rocket-based server? (something like `my_rocket_instance::shutdown()`)

TIA for any help!

**Comment by jebrosen** [comment] 2020-02-28 18:03
It's been determined to be impossible in 0.4, or at least nobody is interested in working on it - see https://github.com/SergioBenitez/Rocket/issues/180#issuecomment-588483359. The docs you linked are for the `async` branch, which will be included in rocket 0.5.

(Closing as a duplicate of #180)

**Closed by jebrosen** 2020-02-28 18:03 UTC

**Comment by silvioprog** [comment] 2020-02-29 15:03
I can't understand that Rocket users can't stop their servers programmatically. 😕

After that answer, I can realize that a Rocket application requires a terminal all the time, i.e it cannot run as service or daemon in any OS, even being so ordinary HTTP servers running as in that way, which must use a shutdown feature.

My application is going to be published in production and *must* run as service/daemon, since it is an HTTP server. And now I have no way to revert the project to use another framework that implements the ordinary shutdown feature. I'll try something like `taskkill`... I would not like to use this workaround, but apparently I have no choice. 😕

**Comment by jebrosen** [comment] 2020-02-29 16:13
> I can't understand that Rocket users can't stop their servers programmatically.

I should clarify: it's not possible to *gracefully* stop the server programmatically; [`std::process::exit`](https://doc.rust-lang.org/nightly/std/process/fn.exit.html) is always an option.

> After that answer, I can realize that a Rocket application requires a terminal all the time, i.e it cannot run as service or daemon in any OS, even being so ordinary HTTP servers running as in that way, which must use a shutdown feature.

I don't agree with this - Rocket does not "require" a terminal, and if any documentation implies that, it should be fixed. However that is separate from daemon management including shutdown. `systemd`, for example, defaults to `SIGTERM`, which would be an immediate shutdown. As far as I can tell `taskkill` on windows is similar to either `SIGTERM` or `SIGKILL`.

**Comment by silvioprog** [comment] 2020-02-29 22:12
OK. Now I know the only available solution is exiting the process, so I solved it starting another thread and waiting for it using a `Condvar`, that I can exit it programmatically.
