### ISSUE TITLE
Move to official mongoDB driver

### ISSUE THREAD

**Issue by silvioprog** [SergioBenitez/Rocket#1227] opened 2020-02-10 19:28 UTC
Hi.

The [mongo-rust-driver-prototype](https://github.com/mongodb-labs/mongo-rust-driver-prototype) is now archived and contains the following note:

```
NOTE: This driver is superseded by the official MongoDB Rust driver, and will no longer be updated.
```

so, it would be nice to replace it by the official [mongo-rust-driver](https://github.com/mongodb/mongo-rust-driver) one.

Thank you!

**Comment by jebrosen** [comment] 2020-02-10 19:42
(Duplicate of #1189.)

In 0.5, we will upgrade the integration (or remove it, since mongodb now has its own built-in connection pooling).

**Closed by jebrosen** 2020-02-10 19:42 UTC
Labels: duplicate
