### ISSUE TITLE
Ergonomic way to access mysql pool connections?

### ISSUE THREAD

**Issue by kswope** [SergioBenitez/Rocket#954] opened 2019-03-24 03:30 UTC
[[package]]                                                                                                  
name = "mysql"                                                                                               
version = "14.2.0" 

[[package]]                                                                                                  
name = "rocket"                                                                                              
version = "0.4.0" 

This seems to be the only way I can access and use the pool of mysql conns
```
#[database("mydb")]                                                                                          
pub struct DbConn(mysql::Conn);

#[get("/")]                                                                                                  
fn index(conn: DbConn) -> () {                                                                               
    let DbConn(mut c) = conn;                                                                                  
    // let mut c = conn.0; // even uglier                                                                      
     c.ping();                                                                                                  
} 
```

I expected to be able to do this
```
#[get("/")]                                                                                                  
fn index(conn: DbConn) -> () {                                                                                                                                                    
     conn.ping();                                                                                                  
} 
```
But sadly I get this
```
   |
21 |     conn.ping();
   |     ^^^^ cannot borrow as mutable
```

I think DbConn implements Deref but I don't see how I can use it since, for reasons I don't understand, mysql driver needs conn to be mutable.

I didn't have this problem with diesel because I could just utilize the Deref like this
```
	let results = users
		.filter(id.eq(1))
		.load::<User>(&*conn)
		.expect("didn't work");
```

**Comment by jebrosen** [comment] 2019-03-24 03:34
This is a duplicate of #862, which has been fixed already but isn't yet in a released version.

`c.0.ping()` should still work (but is certainly uglier).

**Closed by jebrosen** 2019-03-24 03:34 UTC
