### ISSUE TITLE
impl FromRequest for &HeaderMap

### ISSUE THREAD

**Issue by cutewalker** [SergioBenitez/Rocket#178] opened 2017-02-07 07:47 UTC
so that we can get request headers easily.

**Comment by SergioBenitez** [comment] 2017-02-08 05:12
This is something that isn't being done by design. It seems a bit odd, and certainly error-prone, that you'd need to fetch a raw header in a handler. The appropriate thing to do here is to implement a request guard that retrieves and validates the header and then use the guard in the handler. Are you familiar with [request guards](https://rocket.rs/guide/requests/#request-guards)? Is there a reason this approach doesn't suffice?

**Comment by cutewalker** [comment] 2017-02-09 07:14
Surely request guards can suffice me and I have done with it.  
I needed return the request headers as the response body, so I thought it would be nice if FromRequest was implemented for &HeaderMap.  
 Using request guards needs some more code and consideration, but is more robust, as you said.

**Comment by SergioBenitez** [comment] 2017-02-09 07:19
This seems like a special case. If you don't mind, why were you returning the headers in the response?

**Comment by cutewalker** [comment] 2017-02-09 11:48
Of course not. I am learning rust and rocket,  and trying to use them to implement [httpbin](https://github.com/Runscope/httpbin) . Returning the headers is here ["/headers"]( http://httpbin.org/headers)

**Comment by SergioBenitez** [comment] 2017-04-18 07:23
It's been a couple of months, and no one else has chimed in in support of this feature. As a result, and because it's simple to implement `FromRequest` for whichever headers you're trying to retrieve, I'm closing this. If you're coming across this issue and would like to see the feature implemented, please feel free to comment so that we can reevaluate it then.

**Closed by SergioBenitez** 2017-04-18 07:23 UTC
Labels: feedback wanted, request

**Comment by vityafx** [comment] 2019-08-27 07:19
Could you please explain how can I get user agent in a handler then? It is a request header and if I can't take it, and I need to store in the database. So my handler should look like:

```rust
#[get("/<user_id>")]
fn get_user(user_id: Id, user_agent: UserAgent);
```

By the way, I also need other fields from headers. How do I do this? This was not mentioned in the documentation, only request guards, but this is now what I need, I think (I may be wrong).

**Comment by levinotik** [comment] 2019-11-10 06:39
This would be nice to have or at least an example of how to do it. Bit confused myself how to implement this. Would like Map of headers so I can echo in response.

**Comment by jebrosen** [comment] 2019-11-10 22:29
It is possible and pretty simple to implement something like `struct AllHeaders<'a, 'r>(&'a HeaderMap<'r>); impl FromRequest<'a, 'r> for Headers<'a, 'r>` if you do actually need *all* the headers. It's not provided because it is a relatively unusual use case; nearly anything that reads header(s) should be implemented as a request guard, which provides better re-usability and safety.

**Comment by levinotik** [comment] 2019-11-11 02:28
Thanks @jebrosen Just need to get a bit better at Rust so your little example actually helps a lot :P thanks!
