### ISSUE TITLE
Possible to have dynamic route pattern matching without slashes in between?

### ISSUE THREAD

**Issue by j6k4m8** [SergioBenitez/Rocket#1261] opened 2020-03-28 15:01 UTC
I'm relatively new to Rocket (and rust as well!) so please have patience with me, I'm trying to communicate this as effectively as possible :) I wasn't able to find any existing issues on the topic.

When creating a dynamic path [(docs)](https://rocket.rs/v0.4/guide/requests/#dynamic-paths), I see that I can create as many parameters as I like:

```rust
#[post("/toy/example/<foo>/<bar>/<baz>")]
```

But my understanding is that each route path variable must be delimited by slashes. In other words, the following is not acceptable, because the `<foo>` arg has `FOO` text inside its nearest slashes:

```rust
#[post("/toy/example/FOO<foo>/<bar>/<baz>")]
```

(I've tried a few variants of this, `<foo>!<bar>`, `<foo>_<bar>`, just to make sure that it is indeed _any_ time other text appears in that section of the URL route.)

As a complete route function example, trying to stay as close to the docs as possible:

```rust
#[get("/hello/<name>-<age>")]
fn hello(name: String, age: u8) -> String {
    return format!("Hello, {} year old named {}!", age, name);
}
```

All of the above fail with the following:

```
error: `name>-<age` is not a valid identifier
  --> src/main.rs:14:15
   |
14 | #[get("/hello/<name>-<age>")]
   |               ^^^^^^^^^^^^
   |
   = help: parameter names must be valid identifiers
```

This message in particular makes me think that there is some pattern matching for `/<` and `>/`. My question is: **Is this a current limitation of Rocket, and is there a way to achieve this functionality in an idiomatic way?**

As a workaround, I'm currently anticipating creating a single var to capture everything in each URL route segment, and then do some string-to-int parsing in the fn body. :( Hoping there's a rustier way!

<small>All code above assuming version 0.4.4.</small>

**Comment by jebrosen** [comment] 2020-03-28 16:23
Yes, this is a current limitation / requested feature: path segments can either be a static string or a single variable parameter, not any mix of them. Some more explanation is at https://github.com/SergioBenitez/Rocket/issues/339#issuecomment-313881149.

For this example, you could create a type representing a person and implement `FromParam`:

```rust
struct Person { name: String, age: u8 }

impl FromParam for Person {
    // TODO: implement
    // split at - and parse the second half as a u8
}

#[get("/hello/<person>")]
fn hello(person: Person) -> String {
    return format!("Hello, {} year old named {}!", person.age, person.name);
}
```

Closing as a duplicate of #339.

**Closed by jebrosen** 2020-03-28 16:23 UTC

**Comment by j6k4m8** [comment] 2020-03-28 19:05
Got it. Sorry for the duplicate, and thank you for the clear explanation!
