### ISSUE TITLE
Accept headers handled wrong

### ISSUE THREAD

**Issue by lheckemann** [SergioBenitez/Rocket#393] opened 2017-08-20 11:17 UTC
### Versions
Rocket 0.3.2 on NixOS 17.03

### Issue details

As far as I can tell, Rocket only handles the first option with the highest quality from the `Accept` header.

Server code:
```rust
use rocket;

#[get("/", format = "application/json")]
fn get() -> &'static str {
    "{}"
}

pub fn serve() {
    rocket::ignite()
        .mount("/", routes![get])
        .launch();
}
```

Tested using `curl -v -H 'Accept: <accept header>' localhost:8000`

Accept header | Expected response | Actual response | Correct?
--- | --- | --- | ---
`*/*` | 200, body `{}` | 200, body `{}` | ✔
`text/html` | 406 Not Acceptable | 404 Not Found (with HTML error page) | ✘
`text/html,application/json` | 200, body `{}` | 404 Not Found (with HTML error page) | ✘
`application/json,text/html` | 200, body `{}` | 200, body `{}` | ✔
`text/html;q=0.8,application/json` | 200, body `{}` | 200, body `{}` | ✔
`text/html;*/*;q=0.8` | 200, body `{}` | 404 Not Found (with HTML error page) | ✘

cf. [definition](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html):

> If no Accept header field is present, then it is assumed that the client accepts all media types. If an Accept header field is present, and if the server cannot send a response which is acceptable according to the combined Accept field value, then the server SHOULD send a 406 (not acceptable) response. 

I first discovered this issue while trying to test a JSON API endpoint simply by opening it in Firefox, and finding that it returned a 404.

**Comment by SergioBenitez** [comment] 2017-08-22 08:22
As described in [the documentation](https://rocket.rs/guide/requests/#format), the `format` attribute parameter matches against the preferred media type in the `Accept` header for non-payload-bearing requests. For payload-bearing requests, the `format` attribute parameter matches against the `Content-Type` of the request. This is how `format` works, and your tests indicate that it is working exactly as expected.

You're referencing an outdated standard. The up-to-date RFCs for HTTP are 7230 and 7231. Specifically, from [RFC7231 S5.3.2](https://tools.ietf.org/html/rfc7231#section-5.3.2):

> A request without any Accept header field implies that the user agent
   will accept any media type in response.  If the header field is
   present in a request and none of the available representations for
   the response have a media type that is listed as acceptable, the
   origin server can either honor the header field by sending a 406 (Not
   Acceptable) response or disregard the header field by treating the
   response as if it is not subject to content negotiation.

The `format` attribute parameter is meant to be used for content negotiation. For instance, you may have a resource that has a canonical representation of HTML that can also be served as JSON or MessagePack if the client prefers those formats. In Rocket, you could structure this as:

```rust
#[get("/resource", format = "application/msgpack")]
fn get_msgpack() -> MsgPack { .. }

#[get("/resource", format = "application/json")]
fn get_json() -> Json { .. }

#[get("/resource")]
fn get_canonical() -> Html { .. }
```

If instead the `format` attribute worked as you suggest, the `format` would be unusable for content negotiation; it is imperative that `format` matches the _preferred_ media type for content negotiation to be handled properly on Rocket's side.

Because `format` is working as intended, I'm closing out this issue.

**Closed by SergioBenitez** 2017-08-22 08:22 UTC
Labels: invalid

**Comment by lheckemann** [comment] 2017-08-23 05:30
> You're referencing an outdated standard

Indeed, my mistake. However, re this:

> If the header field is present in a request and none of the available representations for the response have a media type that is listed as acceptable, the origin server can either honor the header field by sending a 406 (Not Acceptable) response or disregard the header field by treating the response as if it is not subject to content negotiation.

Rocket isn't doing either of these things. The table in my original issue report describes what it would be doing in the former case; in the latter case, it would still be returning the JSON rather than an error page. Regardless, it isn't performing the content negotiation correctly.

Additionally, the order should not have any effect on choice, as it currently does; There is not necessarily any one preferred media type, but a set of preferred media types, as in the `text/html,application/json` and `application/json,text/html` cases shown in my table above. Consider the example from the RFC:

>   A more elaborate example is
> ```
>    Accept: text/plain; q=0.5, text/html,
>            text/x-dvi; q=0.8, text/x-c
> ```
> Verbally, this would be interpreted as "text/html and text/x-c are the equally preferred media types, but if they do not exist, then send the text/x-dvi representation, and if that does not exist, send the text/plain representation".

Note "equally preferred" — the fact that text/html comes before text/x-c does not mean that it is preferred.

So what I think *should* be matched against is not the preferred media type, but the preferred one amongst the intersection of those listed by the client and those available. Would you consider accepting a PR to implement this? If so I'll have a look at implementing it this weekend.

**Comment by lheckemann** [comment] 2017-08-31 15:59
Started work in [my repo](https://github.com/lheckemann/Rocket/tree/content-negotiation)
