### ISSUE TITLE
example/hello_world build fail on `ring v0.11.0`

### ISSUE THREAD

**Issue by chenjianxin** [SergioBenitez/Rocket#717] opened 2018-07-23 14:08 UTC
OS is win10
rustc version is 1.29.0-nightly (874dec25e 2018-07-21)

when I cargo run Rocket/example/hello_world 
it return 
```
error: failed to run custom build command for `ring v0.11.0`
process didn't exit successfully: `D:\Rocket\target\debug\build\ring-c911c87736bfc837\build-script-build` (exit code: 101)
--- stderr
thread '<unnamed>' panicked at 'execution failed', D:\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\build.rs:658:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'execution failed', D:\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\build.rs:658:9
thread '<unnamed>' panicked at 'execution failed', D:\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\build.rs:658:9
thread '<unnamed>' panicked at 'execution failed', D:\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\build.rs:658:9
thread '<unnamed>' panicked at 'execution failed', D:\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\build.rs:658:9
thread '<unnamed>' panicked at 'execution failed', D:\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\build.rs:658:9

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by luciusmagn** [comment] 2018-07-23 14:34
Sadly, ring 0.11 still fails to build on Windows. This isn't a Rocket a issue.

**Comment by jebrosen** [comment] 2018-07-23 14:38
Duplicate of #457 and/or #642. The next release of Rocket will have ring 0.13 in its dependency chain, which is compiling successfully on Windows.

**Closed by jebrosen** 2018-07-23 14:38 UTC
