### ISSUE TITLE
FormItems doesn't url decode form_string

### ISSUE THREAD

**Issue by JDemler** [SergioBenitez/Rocket#135] opened 2017-01-14 14:44 UTC
When implementing the `FromForm` trait one is advised to use the `FormItems` iterator which is really handy.

In my case though, the form is "application/x-www-form-urlencoded" and the `FormItems`-iterator doesn't url-decode the form contents as I would have expected it to do.

I could use [url::form_urlencoded::parse](https://docs.rs/url/1.2.4/url/form_urlencoded/fn.parse.html) but for me it feels like rocket should handle that.

So, is this intended behaviour or a missing feature?

**Comment by SergioBenitez** [comment] 2017-01-14 15:49
This is the intended behavior. Who knows what you want to do with the form values?

If you want to URL decode, just use `String::from_form_value(value)`. Like this:

```rust
for (key, value) in FormItems(my_form_string) {
    let decoded = String::from_form_value(value);
    ....
}
```

**Comment by SergioBenitez** [comment] 2017-01-15 10:30
I've documented this behavior and have included an example on how to use `String::from_form_value` in https://github.com/SergioBenitez/Rocket/commit/cf82469c527a23d1db88aaf99c285db4cacd60c6. Closing this as a result. If you feel your question is unanswered, please feel free to reopen this issue.

**Closed by SergioBenitez** 2017-01-15 10:30 UTC
Labels: question

**Comment by JDemler** [comment] 2017-01-15 18:24
Thank you for clarifing and documenting the current situation.
Nevertheless, I do not agree with your decision: What else would one want to do with an encoded form other than decode it. If any other operation would be necessary, one still had the raw-string to operate upon.

The new part of the documentation also forgets to mention, that keys can be url encoded, too.

Also, `String::from_form_value` introduces a clone in every case whereas `url::form_urlencoded::parse` only introduces them when necessary. 

This is most certainly nitpicking. Nevertheless, for correctly operating on an url-encoded form one currently has to url-decode key as well as value which introduces two meaningless lines of code plus two, possibly unneccesary, allocations. 

The alternative `url::form_urlencoded::parse` seems to be the better solution.
