### ISSUE TITLE
No `secret_key` is configured

### ISSUE THREAD

**Issue by kariae** [SergioBenitez/Rocket#962] opened 2019-04-04 06:18 UTC
Hello I'm running `Rocket v0.4.0` I'm trying to use it in production environment so when I generate a binary with `cargo build --release` normally it should switch Rocket to `prod` mode I guess, and when I run the server I have this in the logs 
```
Configured for production.
    => address: 0.0.0.0
    => port: 8000
    => log: critical
    => workers: 8
    => secret key: generated
    => limits: forms = 32KiB
    => keep-alive: 5s
    => tls: disabled
Warning: environment is 'production', but no `secret_key` is configured
🚀 Rocket has launched from http://0.0.0.0:8000
```

Knowing that I already set `secret_key` in `Rocket.toml` file with a different port for production, so I feel like the `Rocket.toml` is not used here, that's said if I run the application without building it using `ROCKET_ENV=prod cargo run` it uses the `Rocket.toml` configuration, so I'm wondering if I need to add something during the release build?

**Comment by jebrosen** [comment] 2019-04-05 03:59
> I feel like the `Rocket.toml` is not used here

From [the guide](https://rocket.rs/guide/configuration/#rockettoml):

> Rocket searches for the file starting at the current working directory. If it is not found there, Rocket checks the parent directory. Rocket continues checking parent directories until the root is reached.

It sounds like either the server executable or `Rocket.toml` isn't where it is supposed to be.

**Comment by kariae** [comment] 2019-04-06 10:01
Does that mean I need to ship `Rocket.toml` with the binary file?

**Comment by jebrosen** [comment] 2019-04-06 16:42
Yes. Alternatively, you could instead configure rocket with [environment variables](https://rocket.rs/guide/configuration/#environment-variables).

**Comment by kariae** [comment] 2019-04-06 16:48
I think I will go with the [programmatic](https://rocket.rs/guide/configuration/#programmatic) way since I'm not deploying the bin on my own, thanks for the help.

**Comment by jebrosen** [comment] 2019-04-13 16:34
You can query the environment that rocket would use via [`Environment::active`](https://api.rocket.rs/v0.4/rocket/config/enum.Environment.html#method.active).

Closing, since this is intended behavior. Note that #852 is open for revamping and redesigning configuration, including configuration environments and configuration options.

**Closed by jebrosen** 2019-04-13 16:34 UTC
Labels: invalid
