### ISSUE TITLE
Route macro to match zero or more path segments

### ISSUE THREAD

**Issue by WesleyAC** [SergioBenitez/Rocket#1486] opened 2020-11-30 04:09 UTC
I often want to serve a static directory via [rust-embed](https://github.com/pyros2097/rust-embed/). to do this, i write a route like:

```rust
#[get("/<path..>", rank=1)]
fn static_page(path: std::path::PathBuf) -> Option<Response<'static>> {
    // code goes here
}
```

However, if I want to serve up `index.html` for `/`, this route won't help me — `#[get("/<path..>")]` is not called for `/`, so I have to have a separate route specifically for `/`.

It would be nice to provide syntax like `#[get("/<path?..>")]` that would match `/` and return an empty `PathBuf`. If a PR like this would be accepted, I'd be happy to write it.

**Comment by SergioBenitez** [comment] 2020-11-30 06:24
Duplicate of #985.

**Closed by SergioBenitez** 2020-11-30 06:24 UTC
