### ISSUE TITLE
The 'error' attribute conflicts with the 'log' crate macro.

### ISSUE THREAD

**Issue by RazrFalcon** [SergioBenitez/Rocket#686] opened 2018-07-05 17:34 UTC
Mini example:

```rust
#[macro_use] extern crate log;

/// ... 

#[error(404)]
fn not_found() -> T {
    // ...
}
```

```rust
error: macro `error` may not be used in attributes
   --> src/main.rs:208:1
    |
208 | #[error(404)]
    | ^^^^^^^^^^^^^
```

**Rocket**: 0.3.14

**Comment by jebrosen** [comment] 2018-07-05 17:36
Duplicate of #419. Per #681, a fix is coming in 0.3.15.

**Closed by jebrosen** 2018-07-05 17:36 UTC
