### ISSUE TITLE
TLS example test is not correct

### ISSUE THREAD

**Issue by BinAlyan** [SergioBenitez/Rocket#1566] opened 2021-03-08 09:35 UTC
It seems the test does not depend on Rocket.toml so even if there is an invalid key the test will be successful.

Demonstration:

```
$ cd examples/tls
$ rm private/key.pem
$ cargo test
   Compiling tls v0.0.0 (/home/abdullah/Workspace/forks/Rocket/examples/tls)
    Finished test [unoptimized + debuginfo] target(s) in 2.35s
     Running /home/abdullah/Workspace/forks/Rocket/target/debug/deps/tls-1eac40ebf78ab934

running 1 test
test tests::hello_world ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `/home/abdullah/Workspace/forks/Rocket/target/debug/tls`
🔧 Configured for debug.
    => address: 127.0.0.1
    => port: 8000
    => workers: 12
    => keep-alive: 5s
    => limits: bytes = 8KiB, data-form = 2MiB, file = 1MiB, form = 32KiB, string = 8KiB
    => tls: enabled
    => secret key: [zero]
    => temp dir: /tmp
    => log level: normal
    => cli colors: true
🛰  Mounting /:
    => (hello) GET /
Error: Rocket failed to launch due to an I/O error.
    => error reading TLS file `private/key.pem`: No such file or directory (os error 2)
thread 'main' panicked at 'aborting due to i/o error', core/lib/src/error.rs:178:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by SergioBenitez** [comment] 2021-03-10 01:05
TLS keys are only read/parsed at launch-time, when the server listens for TLS connections. Because the local client (as used in the example tests) cannot open a TCP/TLS connection, the TLS keys are never actually checked for validity in tests.

In general, in the config revamp, we'd erred towards only checking the semantic validity of configuration values when they are actually used. For example, a `secret_key` is only validated when the `secrets` feature is enabled; `tls` is only validated when TLS is enabled and in-use. This is safe and secure and reduces the need to configure properties that have no impact on the server.

For TLS, we might imagine at least issuing a warning if TLS is enabled but the server isn't listening as part of "pre-launch" testing, which local clients _do_ do. I can see the upside - tests would fail if TLS is misconfigured - and the downside -  tests which don't actually use TLS fail because of TLS config.

**Comment by SergioBenitez** [comment] 2021-03-18 01:23
Closing as this is working as intended.

**Closed by SergioBenitez** 2021-03-18 01:23 UTC
Labels: feedback wanted
