### ISSUE TITLE
Example code doesn't compile

### ISSUE THREAD

**Issue by zohaad** [SergioBenitez/Rocket#1273] opened 2020-04-12 21:38 UTC
https://rocket.rs/v0.4/guide/requests/#dynamic-paths
```rs
#[get("/hello/<name>")]
fn hello(name: &RawStr) -> String {
    format!("Hello, {}!", name.as_str())
}
```

**Comment by jebrosen** [comment] 2020-04-12 23:22
This looks like a duplicate of #432, which has been fixed but is not yet published to the website. All examples will either include `use` statements or have an easy way to see them.

Luckily, the compiler is able to point out exactly what's wrong here:

```
help: possible candidate is found in another module, you can import it into scope
  |
8 | use rocket::http::RawStr;
```

**Closed by jebrosen** 2020-04-12 23:22 UTC
