### ISSUE TITLE
[Feature Request] unhide `config::RocketConfig`

### ISSUE THREAD

**Issue by derekdreery** [SergioBenitez/Rocket#921] opened 2019-02-10 11:52 UTC
I want to be able to re-use my `Rocket.toml` for some helper cli apps to support my server. I'd like to re-use the parsing and env detection infrastructure (i.e. I'd like to be able to call [`RocketConfig::read`]). I'm currently just using it even though it's hidden, but I'm worried its considered an implementation detail that might change.

Would you consider unhiding it and making semver guarantees?

The doc(hidden) is at [core/lib/src/config/mod.rs#L224].

[`RocketConfig::read`]: https://github.com/SergioBenitez/Rocket/blob/master/core/lib/src/config/mod.rs#L234
[core/lib/src/config/mod.rs#L224]: https://github.com/SergioBenitez/Rocket/blob/master/core/lib/src/config/mod.rs#L224

**Comment by jebrosen** [comment] 2019-03-09 19:39
I think this is a duplicate of #228, which is going to be addressed in #852.

That said, I think `RocketConfig` is unlikely to change significantly until #852 is also addressed.

**Closed** 2019-03-09 19:39 UTC
Labels: duplicate, request
