### ISSUE TITLE
Exit code 3 after adding Diesel postgres fairing

### ISSUE THREAD

**Issue by nathanmerrill** [SergioBenitez/Rocket#1931] opened 2021-10-03 13:53 UTC
**Description**

I'm attempting to build a rocket app backed by a Diesel Postgres database.  However, when I attempt to run the application, it immediately dies:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.56s
     Running `target\debug\sample.exe`
error: process didn't exit successfully: `target\debug\sample.exe` (exit code: 3)
```

**To Reproduce**

Cargo.toml
```
[dependencies]
rocket = "0.5.0-rc.1"
diesel = { version = "1.4.8", features = ["postgres"] }
rocket_sync_db_pools = { version = "0.1.0-rc.1", features = ["diesel_postgres_pool"]}
```

Rocket.toml
```
[global.databases.sample]
url = "postgres://user:password@localhost/sample"
```

main.rs
```
use rocket_sync_db_pools::{database, diesel};
#[macro_use] extern crate rocket;

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

#[launch]
fn rocket() -> _ {
    rocket::build()
        .mount("/", routes![index])
        .attach(MainDbConn::fairing())
}

#[database("sample")]
struct MainDbConn(diesel::PgConnection);
```

The application works if I remove the `attach()` line.  I've also tested the database connection string via diesel cmdline, which works.

**Expected Behavior**

I'd expect either no error, or a more descriptive error than "Exit code 3".

**Environment:**

 - OS: Windows 10
 - Rocket Version: 0.5.0-rc.1

**Comment by leonbohn** [comment] 2021-10-05 10:15
For me on Arch the code is working as-is. Have you verified that the postgresql server is actually running and the configuration for the database connection is correct? However I totally agree that the error should be more descriptive than exit code 3.

**Comment by nathanmerrill** [comment] 2021-10-05 13:03
I've manually run the diesel CLI: `diesel migration run --database-url postgres://user:password@localhost/sample`, and it has successfully created tables in the database.

So, perhaps there is a difference in URL formatting between the two, or some other connection issue that doesn't present itself via cmdline, but I know at least that the postgres database is up and running.

**Comment by nathanmerrill** [comment] 2021-10-05 13:32
Ok, I've done some additional testing, and it feels like a race issue.  I've had launchoff a couple of times, but when it happens feels inconsistent.  I've rebooted, restarted the postgres service, and sometimes that fixes it, sometimes it doesn't.  There doesn't appear to be a rhyme or reason to it that I can tell yet.

**Comment by SergioBenitez** [comment] 2021-10-07 03:46
Is this all of the log information you get? Try running with `ROCKET_LOG=debug`, perhaps `diesel` will give you more information.

Nevertheless, this is a problem with Diesel/Windows/Configuration, not Rocket.

**Comment by shmeeps** [comment] 2021-11-01 05:30
I'm able to re-produce this with Postgres running on a Windows 10 machine as well. I set up a new Rocket project just to remove anything extraneous and ended up with a similar example to the OP.

Postgres logs had the following

```
2021-11-01 00:02:11.499 CDT [9380] LOG:  connection received: host=127.0.0.1 port=1335
2021-11-01 00:02:11.510 CDT [9380] LOG:  connection authenticated: identity="postgres" method=scram-sha-256 (C:/Program Files/PostgreSQL/14/data/pg_hba.conf:87)
2021-11-01 00:02:11.510 CDT [9380] LOG:  connection authorized: user=postgres database=postgres
2021-11-01 00:02:11.512 CDT [9380] LOG:  execute <unnamed>: SET TIME ZONE 'UTC'
2021-11-01 00:02:11.513 CDT [9380] LOG:  execute <unnamed>: SET CLIENT_ENCODING TO 'UTF8'
2021-11-01 00:02:11.611 CDT [18848] LOG:  connection received: host=127.0.0.1 port=1336
2021-11-01 00:02:11.621 CDT [18848] LOG:  connection authenticated: identity="postgres" method=scram-sha-256 (C:/Program Files/PostgreSQL/14/data/pg_hba.conf:87)
2021-11-01 00:02:11.621 CDT [18848] LOG:  connection authorized: user=postgres database=postgres
2021-11-01 00:02:11.624 CDT [18848] LOG:  execute <unnamed>: SET TIME ZONE 'UTC'
2021-11-01 00:02:11.625 CDT [18848] LOG:  execute <unnamed>: SET CLIENT_ENCODING TO 'UTF8'
2021-11-01 00:02:11.644 CDT [252] LOG:  connection received: host=127.0.0.1 port=1337
2021-11-01 00:02:11.646 CDT [14028] LOG:  connection received: host=127.0.0.1 port=1338
2021-11-01 00:02:11.655 CDT [252] LOG:  connection authenticated: identity="postgres" method=scram-sha-256 (C:/Program Files/PostgreSQL/14/data/pg_hba.conf:87)
2021-11-01 00:02:11.655 CDT [252] LOG:  connection authorized: user=postgres database=postgres
2021-11-01 00:02:11.656 CDT [14028] LOG:  connection authenticated: identity="postgres" method=scram-sha-256 (C:/Program Files/PostgreSQL/14/data/pg_hba.conf:87)
2021-11-01 00:02:11.656 CDT [14028] LOG:  connection authorized: user=postgres database=postgres
2021-11-01 00:02:11.657 CDT [252] LOG:  execute <unnamed>: SET TIME ZONE 'UTC'
2021-11-01 00:02:11.658 CDT [252] LOG:  execute <unnamed>: SET CLIENT_ENCODING TO 'UTF8'
2021-11-01 00:02:11.658 CDT [14028] LOG:  execute <unnamed>: SET TIME ZONE 'UTC'
2021-11-01 00:02:11.659 CDT [14028] LOG:  execute <unnamed>: SET CLIENT_ENCODING TO 'UTF8'
2021-11-01 00:02:11.681 CDT [22260] LOG:  connection received: host=127.0.0.1 port=1339
2021-11-01 00:02:11.683 CDT [11924] LOG:  connection received: host=127.0.0.1 port=1340
2021-11-01 00:02:12.056 CDT [252] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
2021-11-01 00:02:12.056 CDT [11924] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
2021-11-01 00:02:12.056 CDT [252] LOG:  disconnection: session time: 0:00:00.419 user=postgres database=postgres host=127.0.0.1 port=1337
2021-11-01 00:02:12.056 CDT [9380] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
2021-11-01 00:02:12.056 CDT [18848] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
2021-11-01 00:02:12.056 CDT [22260] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
2021-11-01 00:02:12.056 CDT [14028] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
2021-11-01 00:02:12.056 CDT [9380] LOG:  disconnection: session time: 0:00:00.563 user=postgres database=postgres host=127.0.0.1 port=1335
2021-11-01 00:02:12.056 CDT [14028] LOG:  disconnection: session time: 0:00:00.418 user=postgres database=postgres host=127.0.0.1 port=1338
2021-11-01 00:02:12.056 CDT [18848] LOG:  disconnection: session time: 0:00:00.451 user=postgres database=postgres host=127.0.0.1 port=1336
```

Which seems to indicate that the pool is disconnecting before all the connections have been established. Increasing my `timeout` setting doesn't change anything, so it appears that something is acting as if it detected an error. It could be that the pool manager has a bug, or it could be that my Postgres instance acts weird processing that many simultaneous connections. Either way, I would agree this is likely an issue with diesel-r2d2 or r2d2, not anything within Rocket.

I only rarely use this machine for development, so simply limiting [`pool_size`](https://api.rocket.rs/master/rocket_sync_db_pools/struct.Config.html) to 2-3 stops the issue from persisting and works well enough.

**Comment by AcrylicShrimp** [comment] 2021-11-08 16:41
I reported it on https://github.com/diesel-rs/diesel/discussions/2947.

**Comment by weiznich** [comment] 2021-11-10 11:16
Diesel maintainer here.

This seems to be an platform specific issue either in diesel or in libpq. Neither `r2d2` nor `rocket` is needed to reproduce this. See https://github.com/diesel-rs/diesel/discussions/2947 for details.

As I do not have a windows 10 machine for development it would be really helpful to get some help tracking down this issue from the people affected by this. See the linked thread for details about information we are looking for, maybe you can help tracking down this issue.

**Comment by SergioBenitez** [comment] 2022-05-03 13:58
It looks like there's a platform solution at https://github.com/diesel-rs/diesel/discussions/2947#discussioncomment-2025857. Since there isn't anything to fix in Rocket, I'm closing this out.

**Closed by SergioBenitez** 2022-05-03 13:58 UTC
Labels: upstream

**Comment by Adimac93** [comment] 2022-05-13 16:56
Same issue with actix and diesel::r2d2

**Comment by t36campbell** [comment] 2023-09-08 03:32
Late to the party. I solved this by running the app inside docker 

```
FROM rust:latest

WORKDIR /app

COPY . .

RUN cargo build --release

CMD ["./target/release/backend"]
```

**Comment by KingFerris** [comment] 2023-11-14 07:48
I came across this similar error while working with Actix-Diesel-Postgres

I re-started the postgres services from services.msc(windows10)

**Comment by KingFerris** [comment] 2023-11-14 09:01
Quick question, how to gracefully shutdown, actix server and close any postgres connections still open ?
