### ISSUE TITLE
GET should support payloads

### ISSUE THREAD

**Issue by kitsuneninetails** [SergioBenitez/Rocket#731] opened 2018-08-10 01:57 UTC
Currently, when trying to specify a `data` field for a GET route:

```
    #[get("/testGetBody", data="<data>", )]
    fn test_get_body(data: String) -> String {
        format!("{}-SUCCESS", data)
    }
```

This error is generated at compile time:

```
   Compiling http-api-server v0.1.0 (file:///home/micucci/src/git/paidyx/http-api-server-rust)
error: `data` route parameters can only be used with payload supporting methods
   --> src/lib.rs:371:27
    |
371 |     #[get("/testGetBody", data="<data>")]
    |                           ^^^^^^^^^^^^^
    |
    = note: 'GET' does not support payloads
```

However, according to the HTTP Spec section 4.3:

```
 The presence of a message-body in a request is signaled by the
   inclusion of a Content-Length or Transfer-Encoding header field in
   the request's message-headers. A message-body MUST NOT be included in
   a request if the specification of the request method (section 5.1.1)
   does not allow sending an entity-body in requests. 
```

Section 9.3 (GET) has no verbiage forbidding a message-body entity (other sections, like TRACE, specifically forbid it).

This is discussed here:

https://stackoverflow.com/questions/2064281/sending-post-data-with-get-request-valid

For an example, the ElasticSearch API allows a GET with an entity body.  And the spec does not preclude it.  Even though it is not common, and many people have varying opinions on whether it "should" be done, because it is allowed by the standard, I feel a framework like Rocket should allow it, and let the framework user decide whether to implement it or not.

**Comment by SergioBenitez** [comment] 2018-08-10 03:04
Duplicate of #622, and already fixed in master.

**Closed** 2018-08-10 03:04 UTC
