### ISSUE TITLE
`rocket_db_pools` : Upgrade `sqlx` to `0.6`

### ISSUE THREAD

**Issue by griffi-gh** [SergioBenitez/Rocket#2335] opened 2022-09-07 15:43 UTC
**Existing Functionality**

`sqlx` 0.5 is a bit outdated and 0.6 added some useful features, for example `#[sqlx(flatten)]`

**Suggested Changes**

 Upgrade `sqlx` in `rocket_db_pools` to `0.6`

**Alternatives Considered**

\-

**Additional Context**

\-

**Comment by edgarogh** [comment] 2022-09-07 16:06
Duplicate of #2249 (& PR #2242)

**Closed** 2022-09-18 08:47 UTC
Labels: suggestion
