### ISSUE TITLE
A compile error: attempted to take value of method `lo` on type `syntax_pos::Span`

### ISSUE THREAD

**Issue by dannypsnl** [SergioBenitez/Rocket#441] opened 2017-09-26 01:37 UTC
## Bug Reports

Bug reports _must_ include:

  1. The version of Rocket you're using. Ensure it's the latest, if possible.
I am using v0.3.2
And I had make sure I had type following command to make sure I am using nightly Rust.
```bash
$ rustup override set nightly
$ rustup update && cargo update
```

  2. The operating system (distribution and version) where the issue occurs.
Ubuntu 16.04

  3. A brief description of the bug that includes:
    * The nature of the bug.
    * When the bug occurs.
Cargo build
    * What you expected vs. what actually happened.
Expected:
rocket_codegen should build success.
Actually happened:
error[E0615]: attempted to take value of method `lo` on type `syntax_pos::Span`
  --> /home/routedan/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket_codegen-0.3.2/src/utils/span_ext.rs:22:14
   |
22 |         self.lo = self.lo + BytePos(length as u32);
   |              ^^
   |
   = help: maybe a `()` to call it is missing?
18 error, all about .lo problem

  4. How you uncovered the bug. Short, reproducible tests are especially useful.
When I am using bitbucket's pipeline, it tell me compile error about this.
And then I try it on my computer. Then found the error.

  5. Ideas, if any, about what Rocket is doing incorrectly.
I think it could be this site says. https://michael-f-bryan.github.io/rustc-internal-docs/syntax_pos/struct.Span.html
```
lo: BytePos
Deprecated since 1.21: use getters/setters instead
```

**Comment by SergioBenitez** [comment] 2017-09-26 02:23
Confirmed breakage due to the new nightly. You caught this before the CI did! Fix with a new release is incoming.

**Comment by dannypsnl** [comment] 2017-09-26 02:25
But why on my computer also meet this problem?

**Comment by SergioBenitez** [comment] 2017-09-26 04:13
Rocket v0.3.3 has been released with an update for this and more.

**Closed by SergioBenitez** 2017-09-26 04:13 UTC
Labels: nightly breakage
