### ISSUE TITLE
Request: direct access for non-async database connection in fairings

### ISSUE THREAD

**Issue by BinAlyan** [SergioBenitez/Rocket#1569] opened 2021-03-10 09:37 UTC
I read [here](https://rocket.rs/master/guide/state/#databases) that in version 0.5.0-dev, to avoid blocking in routes rocket uses run() in database guards.

> The database engines supported by #[database] are synchronous. Normally, using such a database would block the thread of execution. To prevent this, the run() function automatically uses a thread pool so that database access does not interfere with other in-flight requests.

However, in 0.4 I used to perform database initialization in fairings and similarly I used to spawn a thread (that should live as long as the server) with a connection to the database. It would be more convenient in if in fairings rocket 0.5 allowed direct, non-async access to the database connection similar to 0.4.

The async db access complicates my existing blocking code. My first attempt for doing it is very wrong:
```
    let conn = DbConn::get_one(&rocket).await.expect("database connection");

    tokio::spawn(async move {
        conn.run(|conn| {
            thread_which_does_not_terminate(&conn);
        })
        .await
    });
```

**Comment by jebrosen** [comment] 2021-03-11 02:00
I think this is a duplicate of #1187.

> similarly I used to spawn a thread (that should live as long as the server) with a connection to the database

I am actually a bit surprised this worked before! One of the features of a connection pool is to automatically recycle connections that have broken or timed out.

**Closed by jebrosen** 2021-03-11 02:00 UTC
