### ISSUE TITLE
Capturing all values of multiple instance query params

### ISSUE THREAD

**Issue by Johnlon** [SergioBenitez/Rocket#621] opened 2018-05-03 00:46 UTC
In some cases we have a query string like "?arg=A&arg=B"

When grabbing the value of query parameter "arg" I want to get back a list of the values ["A","B"] not a single value.

How is this achieved?

**Comment by maxdeviant** [comment] 2018-05-03 04:44
My intuition says it would look something like this:

```rust
#[derive(FromForm)]
struct MultipleParams {
    args: Vec<String>
}
```

But that fails with:

```sh
the trait `rocket::request::FromFormValue<'_>` is not implemented for `std::vec::Vec<std::string::String>`
```

There probably needs to be a discussion about what Rocket should do in this case.

**Comment by maxdeviant** [comment] 2018-05-03 04:56
This appears to be a duplicate of #205, with further discussion taking place in #608.

**Comment by Johnlon** [comment] 2018-05-03 09:35
Yes tried same intuitive approach and failed

**Comment by SergioBenitez** [comment] 2018-05-05 07:54
This is indeed #205. There is progress being made to support exactly what you've tried. Let's track that in #205.

**Closed by SergioBenitez** 2018-05-05 07:54 UTC
