### ISSUE TITLE
Two bugs in field validations cause error context to return bad or missing fields

### ISSUE THREAD

**Issue by ChristofferEnne** [SergioBenitez/Rocket#2394] opened 2022-11-11 14:35 UTC
**Description**

I uncovered two problems in the field validation code (using `FromForm`):
1. In some cases wrong field name is returned in the error.
2. All errors are not returned.

**To Reproduce**

The two added test cases illustrate the problem.

**Expected Behavior**

The returned error context should contain the errors the field validators return, and they should match the field names they are attached to.

**Environment:**

Happens on Windows and macOS using latest stable Rust (1.65).

**Additional Context**

No idea, but the problem seems related to passing an argument to the field validator function, so it might be something in rocket_codegen.

Pull request for the test cases: https://github.com/SergioBenitez/Rocket/pull/2393

**Comment by SergioBenitez** [comment] 2022-11-12 06:44
So one of these is a bug, the other is a consequence.



> In some cases wrong field name is returned in the error.

This is a bug, and fixed by https://github.com/SergioBenitez/Rocket/commit/8166ad0c7c12ca9a247b38a2273c7c598e06aee6.



> All errors are not returned.

This is not a bug. Validation happens in three stages:
  1. The value is converted via `FromForm`, which may fail. (say, into a `u64`).
  2. _Local_ ad-hoc validators, those that don't depend on other fields, are run.
  3. _Global_ validators, those that _do_ depends on other fields, are run.
  4. 
If there are errors at any stage, they are returned without the remaining validation stages running.

The separation of stages 2 and 3 is documented in the [guide](https://rocket.rs/v0.5-rc/guide/requests/#ad-hoc-validation), though not clearly, and it also isn't reflected in the API docs.

Stage 2 simply cannot running if stage 1 fails because a value of the given type is not available. Stages 2 and 3 _can_ ostensibly be flattened into a single stage which would yield the results expected in the original post. I'm looking into whether there's any issue with doing this as I do agree this is likely the more expected and useful result.

**Closed** 2022-11-19 04:01 UTC
Labels: bug, deficiency
