### ISSUE TITLE
Cannot use LenientForm with query string

### ISSUE THREAD

**Issue by gliheng** [SergioBenitez/Rocket#636] opened 2018-05-09 08:30 UTC
Hi, I'm using rocket 0.3.10, and I want to use LenientForm with query string, in case frontend may add extra query string parameter.

It looks this is not supported? The following code compile with error.

```rust
use rocket::request::LenientForm;

#[cfg(test)] mod tests;

#[derive(FromForm)]
struct Person {
    name: String,
    age: Option<u8>
}

#[get("/hello?<params>")]
fn hello(params: LenientForm<Person>) -> String {
    let person = params.get();
    if let Some(age) = person.age {
        format!("Hello, {} year old named {}!", age, person.name)
    } else {
        format!("Hello {}!", person.name)
    }
}

```

Compile with the following error:
```
error[E0277]: the trait bound `rocket::request::LenientForm<'_, Person>: rocket::request::FromForm<'_>` is not satisfied
  --> examples/query_params/src/main.rs:16:1
   |
16 | #[get("/hello?<params>")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `rocket::request::FromForm<'_>` is not implemented for `rocket::request::LenientForm<'_, Person>`
   |
   = note: required by `rocket::request::FromForm::from_form`

error: aborting due to previous error
```

**Comment by SergioBenitez** [comment] 2018-05-09 08:42
This is a duplicate of #628.

**Closed by SergioBenitez** 2018-05-09 08:42 UTC
