### ISSUE TITLE
site: Paragraph text has a text-shadow from `section` CSS selector

### ISSUE THREAD

**Issue by CodeMan99** [SergioBenitez/Rocket#2472] opened 2023-02-20 15:08 UTC
## Description

When using the _find_ tool in Chrome, the text has a shadow that makes it very difficult to read.

#### With Shadow

![image](https://user-images.githubusercontent.com/6373201/220141414-10f3834c-726c-4955-ba33-986203acbc85.png)

#### No Shadow

![image](https://user-images.githubusercontent.com/6373201/220142401-9e097fdc-3f1c-4476-b72c-0b24c550fba2.png)

**Comment by SergioBenitez** [comment] 2023-03-24 19:21
I completely agree with you. It doesn't seem like there's any way to remove the shadow when the text is highlighted by search. We _can_ remove it when the text is selected via `::selection`, but it doesn't apply to text highlighted by search. I'm closing this, not because I don't want to fix, but because as far as I can tell there's no way to do so. If I'm incorrect, please advise and I'll push a fix ASAP.

**Closed by SergioBenitez** 2023-03-24 19:21 UTC
Labels: triage

**Comment by trybick** [comment] 2023-03-27 13:15
@SergioBenitez Question on this - that `text-shadow` style can be found in the site's CSS file. Maybe where that CSS file is coming from would be an answer. Where is that CSS controlled? 

To me it appears that style is appearing when using Find, and not even mouse selecting it.

<img width="562" alt="Screenshot 2023-03-27 at 9 11 15 AM" src="https://user-images.githubusercontent.com/39889198/227947960-b84c582d-e651-41a0-b6c1-20f183f24391.png">

**Comment by trybick** [comment] 2023-03-27 13:15
@SergioBenitez Question on this - that `text-shadow` style can be found in the site's CSS file. Maybe where that CSS file is coming from would be an answer. Where is that CSS controlled? 

To me it appears that style is appearing when using Find, and not even mouse selecting it.

<img width="562" alt="Screenshot 2023-03-27 at 9 11 15 AM" src="https://user-images.githubusercontent.com/39889198/227947960-b84c582d-e651-41a0-b6c1-20f183f24391.png">

**Comment by trybick** [comment] 2023-03-27 13:15
@SergioBenitez Question on this - that `text-shadow` style can be found in the site's CSS file. Maybe where that CSS file is coming from would be an answer. Where is that CSS controlled? 

To me it appears that style is appearing when using Find, and not even mouse selecting it.

<img width="562" alt="Screenshot 2023-03-27 at 9 11 15 AM" src="https://user-images.githubusercontent.com/39889198/227947960-b84c582d-e651-41a0-b6c1-20f183f24391.png">

**Comment by SergioBenitez** [comment] 2023-03-27 14:14
@trybick I wrote the CSS manually. I can certainly remove the shadow altogether, this isn't the problem, the issue is that there's no way to do so only when the text is highlighted by the browser's search interface. The text shadow is _always_ there, it just looks quite bad when combined with the highlight from searching.
