### ISSUE TITLE
error build "rocket_http" in last update.

### ISSUE THREAD

**Issue by Darkkaiserl** [SergioBenitez/Rocket#1361] opened 2020-06-29 18:58 UTC
i update dependency, and rocket_http don't compile now.

Rust: nightly-x86_64-pc-windows-msvc unchanged - rustc 1.46.0-nightly (2f517ce6f 2020-06-28).

``` rust
let path_and_query = pear_try!(path_and_query(is_pchar));
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
= help: message: called `Option::unwrap()` on a `None` value
```

**Comment by jebrosen** [comment] 2020-06-29 19:01
This looks like a duplicate of #1358 - `cargo update` should solve your error.

**Closed by jebrosen** 2020-06-29 19:01 UTC
