### ISSUE TITLE
Graceful termination of Rocket application

### ISSUE THREAD

**Issue by antekone** [SergioBenitez/Rocket#776] opened 2018-09-18 08:54 UTC
I'm using Rocket 0.3.16.

Is there a way to make Rocket break its main loop and quit the application gracefully?

I'm trying to convert my Rocket application to a Windows Service. A Windows Service apparently needs Rocket application to be spawned in a different thread, and reserve its main thread to receive/process Windows Service events. To properly handle the Stop signal, the main application should terminate the Rocket thread gracefully, so I can't simply use `std::process:exit()`.

I couldn't find any mention of how to quit the Rocket app. The documentation only says that the `Rocket::launch()` function never returns, so this might be unsupported?

Currently I'm using conditional compilation on Windows; I'm importing `kernel32` crate, and I'm performing an `unsafe` call to `TerminateThread`. It's nowhere near the proper solution and I'd like to change it.

**Comment by jebrosen** [comment] 2018-09-19 01:50
Clean shutdown is desired at some point (see #180). Today, though, I think non-graceful termination through TerminateThread or spawning a Rocket server in a child process to kill later is the only working solution.

**Comment by SergioBenitez** [comment] 2018-09-19 02:49
Closing as a duplicate of #180.

**Closed by SergioBenitez** 2018-09-19 02:49 UTC
Labels: duplicate
