### ISSUE TITLE
Introduce `cookie_private` for `LocalRequest`

### ISSUE THREAD

**Issue by madeindjs** [SergioBenitez/Rocket#488] opened 2017-12-01 07:10 UTC
# Feature request

Currently to run local test with cookie you should use [`cookie`](https://api.rocket.rs/rocket/local/struct.LocalRequest.html#method.cookie) method.

Example

```rust
#[test]
fn should_not_redirect_on_get_new_recipe() {
    let client = Client::new(rocket()).unwrap();
    let request = client.get("/recipes/new").cookie(
        Cookie::new("user_id", "1"),
    );
    let response = request.dispatch();
    assert_eq!(response.status(), Status::Ok);
}
```

But nothing exists to create **private cookie** like [`add_private`](https://api.rocket.rs/rocket/http/enum.Cookies.html#method.add_private) for [`rocket::http::Cookies`](https://api.rocket.rs/rocket/http/enum.Cookies.html).

What do you think of?

**Comment by madeindjs** [comment] 2017-12-01 07:13
I just saw this opening Pull Request #487

**Comment by SergioBenitez** [comment] 2017-12-02 08:47
Duplicate of #368.

**Closed by SergioBenitez** 2017-12-02 08:47 UTC
Labels: duplicate
