### ISSUE TITLE
Rocket fails to build on Windows with VS 2017 15.7

### ISSUE THREAD

**Issue by Gustorn** [SergioBenitez/Rocket#645] opened 2018-05-20 21:41 UTC
**Rocket version:** 0.3.11 (latest)
**Operating system:** Windows 10
**VS/MSVC++ version:** VS 2017 15.7.1 / v14.14

Because of the transitive dependency on `ring` (through `cookie-rs`), `rocket` fails to build on the latest MSVC++ versions. The cause is some additional warnings (that are being treated as errors, as per the settings in the `ring` build script), example:

```
<USER>\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.11.0\crypto\ec\gfp_p384.c(224) : warning C5045: Compiler will insert Spectre mitigation for memory load if /Qspectre switch specified
 ```

This was already reported and fixed in the `ring` repo as briansmith/ring#648 but the `cookie` library version that `rocket` uses depends on `ring:0.11.0`.

**Comment by SergioBenitez** [comment] 2018-05-20 21:48
Duplicate of #457, #642.

**Closed by SergioBenitez** 2018-05-20 21:48 UTC

**Comment by adubois** [comment] 2018-10-12 13:34
Hi @SergioBenitez the latest crate with tag 3.4.17 still has the ring v0.11 issue related to Spectre warning on Windows.
This is due to cookie-rs 0.9.1 dependency. It needs at least 0.11 (which point to ring 0.12 which fix the issue). I'm not sure how much effort it is to release 3.4.18 (I haven't tested if this is the only problem). But it would help windows new starter to get going with rocket.

**Comment by jebrosen** [comment] 2018-10-13 01:05
@adubois As explained in several other issues here, `rocket` *cannot* update its `ring` dependency until `rocket-0.4`. Updating `ring` would let some users compile rocket that couldn't before, but it would also break many existing projects.
