### ISSUE TITLE
Auto-generate `OPTIONS` handler if not present

### ISSUE THREAD

**Issue by jhpratt** [SergioBenitez/Rocket#961] opened 2019-04-03 03:26 UTC
1. Why you believe this feature is necessary.
2. A convincing use-case for this feature.

To avoid rehashing arguments for the `OPTIONS` verb, I'll leave this one to a simple search. [Her's one](http://zacstewart.com/2012/04/14/http-options-method.html) blog post from 2012 showing how the verb can provide insightful metadata about the endpoint. At the least, returning the allowed methods is better than a 404.

3. Why this feature can't or shouldn't exist outside of Rocket.

I'm not sure if this can be done with a fairing, as it requires information about all endpoints (even those _not_ being requested). I'm not terribly familiar with Rocket's internals, so I could very well be wrong on this one. Regardless, having a flag to turn on a feature like this would improve anyone creating a REST API using Rocket.

**Comment by jebrosen** [comment] 2019-04-04 01:33
This is essentially a duplicate of #25 - which has been accepted, but it's not decided yet what Rocket should do "out of the box". Notably, you never mentioned CORS which is the other main reason this is requested.

> I'm not sure if this can be done with a fairing, as it requires information about all endpoints (even those *not* being requested).

All [mounted routes](https://api.rocket.rs/v0.4/rocket/struct.Rocket.html#method.routes) can be enumerated at certain points during initialization. This might fit your use case, but it might be tricky when there are colliding/ranked routes, path segment matches (i.e. `<path..>`), or already-existing OPTIONS routes.

**Closed by jebrosen** 2019-04-04 01:33 UTC
