### ISSUE TITLE
Cannot return JSON (the trait `serde::ser::Serialize` is not implemented)

### ISSUE THREAD

**Issue by shalugin** [SergioBenitez/Rocket#302] opened 2017-05-29 10:34 UTC
I made a small example to try return JSON from rocket.

Cargo.toml
```
[package]
authors = ["Alexandr Shalugin"]
name = "rocket-json"
version = "0.1.0"

[dependencies]
rocket = "0.2.7"
rocket_codegen = "0.2.7"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"

[dependencies.rocket_contrib]
default-features = false
features = ["json"]
version = "0.2.7"
```

main.rs

```
#![feature(plugin)]
#![plugin(rocket_codegen)]

extern crate rocket;
extern crate serde_json;
#[macro_use]
extern crate rocket_contrib;
#[macro_use]
extern crate serde_derive;

use rocket_contrib::{JSON, Value};

#[derive(Serialize, Debug)]
pub struct Example {
    x: u32,
}

#[get("/")]
fn index() -> JSON<Example> {
    let result = Example { x: 42 };
    println!("{}", serde_json::to_string(&result).unwrap());
    JSON(result)
}

fn main() {
    rocket::ignite().mount("/", routes![index]).launch();
}

``` 

Rust version: nightly-x86_64-pc-windows-msvc unchanged - rustc 1.19.0-nightly (d47cf08d5 2017-05-28)

The build log:

```
error[E0277]: the trait bound `Example: serde::ser::Serialize` is not satisfied
  --> src\main.rs:18:1
   |
18 | #[get("/")]
   | ^^^^^^^^^^^ the trait `serde::ser::Serialize` is not implemented for `Example`
   |
   = note: required because of the requirements on the impl of `rocket::response::Responder<'_>` for `rocket_contrib::JSON<Example>`
   = note: required by `rocket::handler::<impl rocket::Outcome<rocket::Response<'r>, rocket::http::Status, rocket::Data>>::of`

error: aborting due to previous error(s)

```

There no errors in string `println!("{}", serde_json::to_string(&result).unwrap());
`
Is it a bug in rocket?
I can return String serialized by serde_json::to_string, but it's not convenient.

**Comment by Eijebong** [comment] 2017-05-29 10:36
You'e using serde 1.0 with rocket 0.2, you should either use serde 0.9 or rocket on the master branch (rocket with serde 1.0 support hasn't been released yet)

**Comment by shalugin** [comment] 2017-05-29 10:41
@Eijebong Thank you!

**Comment by shalugin** [comment] 2017-05-29 10:50
BTW, link in official documentation (https://rocket.rs/guide/responses/#json) is broken.

> For a complete example, see the JSON example on GitHub.

redirect to https://github.com/SergioBenitez/Rocket/tree/v0.2.7/examples/json (404)

**Comment by SergioBenitez** [comment] 2017-05-29 20:07
@shalugin Ah, thank you for reminding me to create the tag! Should be fixed now.

**Comment by SergioBenitez** [comment] 2017-05-29 20:09
Closing as a duplicate of #273, #278, and #287. `0.3` couldn't come soon enough!

**Closed by SergioBenitez** 2017-05-29 20:09 UTC
Labels: duplicate

**Comment by itsdalmo** [comment] 2017-05-31 07:42
Sorry for commenting on a closed issue @SergioBenitez - I ran into the same problem as described here, and I'm a little confused about why e.g.:

- The `rocket_contrib` version on crates.io is `0.2.7`, and the `serde_json` version dependency is listed as `^0.9.3`.
- The [Cargo.toml](https://github.com/SergioBenitez/Rocket/blob/master/contrib/Cargo.toml#L31) for `rocket_contrib` on master branch is also listed as version `0.2.7`, but version `1.0` of serde_json.

Shouldn't the semver be bumped somehow? To make it more clear that master branch is different from the crates.io release?
