### ISSUE TITLE
Status of 0.3 release

### ISSUE THREAD

**Issue by shssoichiro** [SergioBenitez/Rocket#307] opened 2017-06-02 14:03 UTC
I'm opening this issue not to nag, but because I have an actual need for 0.3 to be released:

`rocket-contrib` 0.2 still requires `serde` 0.9. The `jsonwebtoken` crate now requires `serde` 1.0, and I cannot use an older version of that crate because its dependency, `ring`, yanks older versions. So in order to use `jsonwebtoken` with `rocket-contrib`, rocket 0.3 needs to be released.

**Comment by mgeorgehansen** [comment] 2017-06-02 21:37
We also just got bit by the recent yanking of `ring ^0.7` and lack of `serde 1.0` support in rocket-contrib. Not` rocket-contrib`'s fault by any means, but `serde 1.0` support just became a lot more important for us since it is blocking updates.

**Comment by SergioBenitez** [comment] 2017-06-07 19:33
I'm as eager for `0.3` to be released as you are!

In short: `0.3` will be released within a week, ideally before the end of this one.

There is one issue left to close: #20, which is already finalized in a local branch. Once the issue is closed, documentation updates and polishing will commence. Once docs are ready, `0.3` will ship! It's a big one, and I'm incredibly excited to get it out the door.

In the meantime, and if you're willing to deal with undocumented breaking changes, you can resolve dependency issues by switching to the development branch of Rocket. Thanks to Cargo, this is a simple change to your `Cargo.toml` file:

```toml
[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket.git" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket.git" }
```

I'm going to close this issue out, but feel free to keep commenting here if you'd like!

**Closed by SergioBenitez** 2017-06-07 19:33 UTC

**Comment by jaroslaw-weber** [comment] 2017-07-04 08:55
Any update on 0.3?

**Comment by SergioBenitez** [comment] 2017-07-04 08:57
It's coming! Very soon! While you wait, see the preliminary [`CHANGELOG`](https://github.com/SergioBenitez/Rocket/blob/master/CHANGELOG.md).
