### ISSUE TITLE
Add to Guide information how to get a systemd service calling a rocket binary to read the Rocket.toml file

### ISSUE THREAD

**Issue by jrmiller82** [SergioBenitez/Rocket#1174] opened 2019-11-28 05:43 UTC
I just implemented a rocket microservice and I want to use my custom setting in the Rocket.toml file instead of hard coding environment variables. I couldn't figure out how to get my systemd service / path to get the binary to find the Rocket.toml file for configuration. So for now I have just hardcoded the env variables into the systemd service itself. Just thinking this might be nice to have here such as "make sure you do XYZ on deployment in order for the binary to read Rocket.toml".

**Comment by olback** [comment] 2019-11-28 16:05
Have you set `WorkingDirectory` in your Systemd service?
```
[Service]
...
WorkingDirectory=/path/to/dir/containing/config
```

**Comment by jrmiller82** [comment] 2019-11-28 16:39
Actually, yes, that fixed it. I banged my head on this a bunch, so maybe a "On deployment, make sure to set your systemd WorkingDirectory variable so that the binary can find your Rocket.toml."

**Comment by olback** [comment] 2019-11-28 16:47
I know deploy documentation is being worked on, see #171. I'm, guessing that it's not really a priority though.

**Comment by jrmiller82** [comment] 2019-11-28 16:55
That documentation definitely needs to be added to the project.

**Comment by jebrosen** [comment] 2019-11-28 20:59
Closing as a duplicate of #171, which would definitely resolve this. I consider a working `systemd` unit including `WorkingDirectory` as a baseline example.

**Closed by jebrosen** 2019-11-28 20:59 UTC
