### ISSUE TITLE
v0.4 package resolution fail: pbkdf2 0.2.x has been yanked

### ISSUE THREAD

**Issue by Kinrany** [SergioBenitez/Rocket#1908] opened 2021-09-18 01:06 UTC
**Description**

Cloning and building branch `v0.4` (tag `v0.4.10`) fails at version selection. `rocket_contrib` depends on `mongodb v0.3.12`, which depends on `pbkdf2 ^0.2.0`, which no longer exists.

**To Reproduce**

1. `git clone git@github.com:SergioBenitez/Rocket.git`
2. `git switch v0.4`
3. `cargo build`

**Expected Behavior**

Cloning repository and building from scratch always works.

**Environment:**

 - OS Distribution and Kernel: Ubuntu 20.04 focal, x86_64 Linux 5.11.0-34-generic
 - Rocket Version: 0.4.10, v0.4@08e5b6dd

**Additional Context**

```
kinrany:~/projects/Rocket$ cargo build
    Updating crates.io index
error: failed to select a version for the requirement `pbkdf2 = "^0.2.0"`
candidate versions found which didn't match: 0.9.0, 0.8.0, 0.7.5, ...
location searched: crates.io index
required by package `mongodb v0.3.12`
    ... which is depended on by `rocket_contrib v0.4.10 (/home/kinrany/projects/Rocket/contrib/lib)`
```

Tried `cargo upgrade --workspace mongodb`, but somehow the dependency on `mongodb v0.3.12` stays:

```
kinrany:~/projects/Rocket$ cargo build
    Updating crates.io index
error: failed to select a version for the requirement `pbkdf2 = "^0.2.0"`
candidate versions found which didn't match: 0.9.0, 0.8.0, 0.7.5, ...
location searched: crates.io index
required by package `mongodb v0.3.12`
    ... which is depended on by `r2d2-mongodb v0.2.0`
    ... which is depended on by `rocket_contrib v0.4.10 (/home/kinrany/projects/Rocket/contrib/lib)`
    ... which is depended on by `cookies v0.0.0 (/home/kinrany/projects/Rocket/examples/cookies)`
```

**Comment by jebrosen** [comment] 2021-09-18 16:16
This looks like a duplicate of #1812 (with a different dependency in the message). This unfortunately can't be resolved in a 0.4.x release.

**Closed by jebrosen** 2021-09-18 16:16 UTC
Labels: triage
