### ISSUE TITLE
Custom HTTP methods

### ISSUE THREAD

**Issue by ben-lichtman-msft** [SergioBenitez/Rocket#1817] opened 2021-08-10 22:41 UTC
There are a number of HTTP protocol extensions that I feel would be useful to have rocket support - this includes protocols such as webdav.

Currently it seems that rocket only supports the official HTTP methods and will just reject unsupported methods, and there is no way to build HTTP extensions on top of rocket in any way that I could find.

Is this a feature that rocket may be able to support in the future? or is there some way to support custom methods currently?

**Comment by ben-lichtman-msft** [comment] 2021-08-10 22:45
Closed because this seems a little niche / there are other suitable alternatives

**Comment by jebrosen** [comment] 2021-08-14 17:19
Closing as a duplicate of #232.

**Closed by jebrosen** 2021-08-14 17:19 UTC
Labels: request
