### ISSUE TITLE
Implement the FromRequest trait for the Request type

### ISSUE THREAD

**Issue by vityafx** [SergioBenitez/Rocket#1109] opened 2019-08-29 16:29 UTC
Right now it is impossible to use the `Request` object directly in the handler. The suggestion is to implement the `FromRequest` trait for the `Request` type to make it possible. Also, avoiding this leads to boilerplate handlers:

1. If you need many things from the `Request`, you'll have many parameters in your handler, for example:

    ```rust
    fn handler(cookies, headers, a, b, c) -> ... { ... }
    ```

   where all of the parameters must implement the `FromRequest` trait.

2. You'll need to actually declare all these types and implement almost transparent `FromRequest` trait for them, what is an annoying and meaningless job to do.

Simple accepting a `Request` object in such a handler would do the job perfectly, as you'll only need to access its' methods.

Right now it is possible to achieve by writing this boilerplate code:

```rust
#[derive(Debug, Clone)]
struct RequestHolder<'a, 'r>(pub &'a rocket::Request<'r>);
impl<'a, 'r> AsRef<rocket::Request<'r>> for RequestHolder<'a, 'r> {
    fn as_ref(&self) -> &rocket::Request<'r> {
        &self.0
    }
}
impl<'a, 'r> std::ops::Deref for RequestHolder<'a, 'r> {
    type Target = rocket::Request<'r>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl<'a, 'r> rocket::request::FromRequest<'a, 'r> for RequestHolder<'a, 'r> {
    type Error = ();

    fn from_request(request: &'a rocket::Request<'r>) -> rocket::request::Outcome<Self, Self::Error> {
        rocket::request::Outcome::Success(Self(request))
    }
}

#[rocket::post("/")]
fn open<'a, 'r>(request: RequestHolder<'a, 'r>, state: State<RequestState>) -> Result<Json<Obj>> {
    let cookies = request.cookies();
    let headers = request.headers();
    // ...
}
```

**Comment by jebrosen** [comment] 2019-08-30 01:53
This looks like a duplicate of #675 and #1110 - no need for both an issue and PRs.

**Closed by jebrosen** 2019-08-30 01:53 UTC
Labels: request

**Comment by vityafx** [comment] 2019-08-30 05:24
This is sad. I understand the goals to make people use only request guards, but:

1. There is extra work in doing the same structure. If you need cookies and headers, you'll do a structure for them and implement the `FromRequest` trait, however, you could have just used the `Request` itself if it had been implemented.
2. Such handlers will have too many parameters. In my own code, I have configured `Clippy` to reject functions with more than 4 parameters. So it is also not an option.

While the framework is simple and clean, it does have some gaps in user experience, such as this. While I can provide such structure and implementation holder myself (see the `RequestHolder` above), I can't understand why people should be so strictly limited. If they want to - they can be, if they don't, why to make them do all of this repeatedly, from one project to another, the same code? You allow many good things to do in a simple way, but you also disallow some at the same time.

Thank you for your answer.

**Comment by arjentz** [comment] 2022-05-23 08:26
I understand that this will not be implemented in Rocket, but I was trying to use @vityafx with Rocket `v0.5-rc.2` (slightly modified):
```
#[derive(Debug, Clone)]
struct RequestWrapper<'a, 'r>(pub &'a rocket::Request<'r>);
impl<'a, 'r> AsRef<rocket::Request<'r>> for RequestWrapper<'a, 'r> {
    fn as_ref(&self) -> &rocket::Request<'r> {
        &self.0
    }
}

impl<'a, 'r> rocket::request::FromRequest<'a> for RequestWrapper<'a, 'r> {
    type Error = ();

    fn from_request(request: &'a rocket::Request<'r>) -> rocket::request::Outcome<Self, Self::Error> {
        rocket::request::Outcome::Success(Self(request))
    }
}
```
And I get the following error:
```
$ cargo check
...
error[E0195]: lifetime parameters or bounds on method `from_request` do not match the trait declaration
  --> src/main.rs:33:20
   |
33 |     fn from_request(request: &'a rocket::Request<'r>) -> rocket::request::Outcome<Self, Self::Error> {
   |                    ^ lifetimes do not match method in trait
```
Would there be any way to fix this?

**Comment by the10thWiz** [comment] 2022-05-24 00:16
Short awnser: no. This is an intentional design decision, you should not be getting the whole request object.

If you need part of the request object, most of the parts implement `FromRequest` (e.g. `Origin` implements it, and provides access to the exact URI that was passed to Rocket).

See https://github.com/SergioBenitez/Rocket/discussions/2197#discussioncomment-2794439 for more info.
