### ISSUE TITLE
Could not compile `rocket_codegen` with the latest rust nightly build: no method named `current_level` found for type `&rustc::lint::LateContext<'a, 'tcx>` in the current scope 

### ISSUE THREAD

**Issue by yaadyaad** [SergioBenitez/Rocket#381] opened 2017-08-11 16:08 UTC
Hello, 

I have the same error as has the CI at https://travis-ci.org/SergioBenitez/Rocket

Can you please fix it or provide a work around for it? I am new to Rust and I like Rocket very much in comparison with Iron.

MacOS, latest Rust nightly build.

More details on it:
   Compiling cookie v0.9.1
error[E0599]: no method named `current_level` found for type `&rustc::lint::LateContext<'a, 'tcx>` in the current scope
   --> /Users/dmitry/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket_codegen-0.3.0/src/lints/mod.rs:247:15
    |
247 |         if cx.current_level(UNMOUNTED_ROUTE) != Level::Allow {
    |               ^^^^^^^^^^^^^

error[E0599]: no method named `current_level` found for type `&rustc::lint::LateContext<'a, 'tcx>` in the current scope
   --> /Users/dmitry/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket_codegen-0.3.0/src/lints/mod.rs:253:15
    |
253 |         if cx.current_level(UNMANAGED_STATE) == Level::Allow {
    |               ^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `rocket_codegen`.
warning: build failed, waiting for other jobs to finish...
error: build failed

Thank you,
Dmitry

**Comment by SergioBenitez** [comment] 2017-08-11 16:11
This is caused by an update in the latest Rust nightly. A fix is already in place, and I'm working on a release now; should be ready shortly. If you want to use Rocket immediately, simply revert to yesterday's nightly.

**Comment by SergioBenitez** [comment] 2017-08-11 16:22
Fix is in 721f6204ea167e86fddcabcf3cb41194ca4c64d1.

**Comment by yaadyaad** [comment] 2017-08-11 16:22
Great! Thank you very much for your prompt reply!

**Closed by SergioBenitez** 2017-08-11 16:22 UTC
