### ISSUE TITLE
Question: Logging JSON POST request

### ISSUE THREAD

**Issue by flosse** [SergioBenitez/Rocket#944] opened 2019-03-10 22:41 UTC
I'd like to log the JSON data of some POST requests (at lest for debugging) and I thought that should be easy to do but I couldn't find a solution.
I tried to use fairing (with rocket `v0.4.0`) like this:

```rust
r.attach(AdHoc::on_request("POST logger", |req, data| {
  let mut buffer = String::new();
  data.open().read_to_string(&mut buffer).unwrap();
 // ...
});
```
But the data `cannot move out of borrowed content`. Cloning the data isn't possible.
Could you help me?

**edit**:
Or is there a way to intercept the parsing of a `Json<MyData>` argument to see what data comes in and what is expected?

**Comment by jebrosen** [comment] 2019-03-13 13:03
I think this is really a duplicate of #775 - it's not currently possible to "hook" or chain `Data` guards. I believe your best option for now is to manually reimplement the `FromData` code for `Json` with your modifications. Note that `.read_to_string` is only available in debug mode (for good reason!), so you will need to use some #[cfg] annotations if you want a release-compatible version.

**Closed by jebrosen** 2019-03-13 13:03 UTC
Labels: duplicate, question
