### ISSUE TITLE
Error with post data as String in release builds only

### ISSUE THREAD

**Issue by TheSilvus** [SergioBenitez/Rocket#988] opened 2019-05-04 17:00 UTC
Building the following handler works in debug builds, but not in `--release` builds:

```
#[post("/", data = "<data>")]
fn post(data: String) -> String {
    data
}
```

Error message:
```
error[E0277]: the trait bound `std::string::String: rocket::data::FromDataSimple` is not satisfied
 --> src/main.rs:7:9
  |
7 | fn post(data: String) -> String {
  |         ^^^^^^^^^^^^ the trait `rocket::data::FromDataSimple` is not implemented for `std::string::String`
  |
  = note: required because of the requirements on the impl of `rocket::data::FromData<'_>` for `std::string::String`

error: aborting due to previous error
```

- Rocket version: 0.4.0
- Rust version: 1.36.0-nightly (a340557c 2019-05-03)

**Comment by jebrosen** [comment] 2019-05-04 17:10
Duplicate of #835, #865. See https://api.rocket.rs/v0.4/rocket/data/trait.FromData.html#provided-implementations for the reason.

**Closed by jebrosen** 2019-05-04 17:10 UTC
