### ISSUE TITLE
Add JS/CSS minification?

### ISSUE THREAD

**Issue by GuillaumeGomez** [SergioBenitez/Rocket#692] opened 2018-07-08 23:14 UTC
Hi,

I wrote [minifier-rs](https://github.com/guillaumeGomez/minifier-rs), a small crate to minify JS and CSS. It's currently being used in rustdoc and I'd like, if possible, to get more potential failure/issues feedbacks in order to improve it. Would it be possible to add it into your crate behind a feature so I could get some please?

Thanks in advance!

**Comment by SergioBenitez** [comment] 2018-07-09 00:18
Duplicate of https://github.com/SergioBenitez/Rocket/issues/684.

**Closed by SergioBenitez** 2018-07-09 00:18 UTC
Labels: duplicate
