### ISSUE TITLE
Error: Failed to run database migrations: QueryError(DatabaseError(__Unknown, "near \"OR\": syntax error"))

### ISSUE THREAD

**Issue by tyoc213** [SergioBenitez/Rocket#1666] opened 2021-06-06 22:56 UTC
1. 0.4.10
2. Linux

Running the todo example 

```
base) ✘-101 ~/Documents/explorations/202106/Rocket/examples/todo [v0.4.10|✚ 2…6] 
17:50 $ RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `/home/tyoc213/Documents/explorations/202106/Rocket/target/debug/todo`
🔧 Configured for development.
    => address: localhost
    => port: 8000
    => log: normal
    => workers: 32
    => secret key: generated
    => limits: forms = 32KiB
    => keep-alive: 5s
    => read timeout: 5s
    => write timeout: 5s
    => tls: disabled
    => [extra] template_dir: "static"
    => [extra] databases: { sqlite_database = { url = "db/db.sqlite" } }
Error: Failed to run database migrations: QueryError(DatabaseError(__Unknown, "near \"OR\": syntax error"))
🛰  Mounting /:
    => GET / [10]
    => GET /<path..> [10]
🛰  Mounting /:
    => GET / (index)
🛰  Mounting /todo:
    => POST /todo (new)
    => PUT /todo/<id> (toggle)
    => DELETE /todo/<id> (delete)
Error: Rocket failed to launch due to failing fairings:
    => Database Migrations
thread 'main' panicked at 'launch fairing failure', core/lib/src/error.rs:214:17
stack backtrace:
   0:     0x564a3180baa0 - std::backtrace_rs::backtrace::libunwind::trace::h43710feb0ffcdc8e
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x564a3180baa0 - std::backtrace_rs::backtrace::trace_unsynchronized::h66924da3c11f02b8
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x564a3180baa0 - std::sys_common::backtrace::_print_fmt::h730a74ff441d01d3
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x564a3180baa0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h77a51d96847efeba
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x564a3182e35c - core::fmt::write::h1e5a1f350e43b10f
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/core/src/fmt/mod.rs:1110:17
   5:     0x564a31804f95 - std::io::Write::write_fmt::h34bd961f54930119
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/io/mod.rs:1588:15
   6:     0x564a3180db6b - std::sys_common::backtrace::_print::h45eaa9c2dc059d91
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x564a3180db6b - std::sys_common::backtrace::print::hd4051bbe3e605bdd
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x564a3180db6b - std::panicking::default_hook::{{closure}}::h200454f5459fec27
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/panicking.rs:208:50
   9:     0x564a3180d641 - std::panicking::default_hook::he575e5de63df333f
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/panicking.rs:225:9
  10:     0x564a3180e211 - std::panicking::rust_panic_with_hook::hcefec3363e176af9
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/panicking.rs:622:17
  11:     0x564a31601cc3 - std::panicking::begin_panic::{{closure}}::hb54975a6d69c7bfa
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/panicking.rs:542:9
  12:     0x564a31607aa9 - std::sys_common::backtrace::__rust_end_short_backtrace::hc4b5d0cf2b78aa9f
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x564a31601bf9 - std::panicking::begin_panic::h12ab8af922f23433
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/panicking.rs:541:12
  14:     0x564a31571dd6 - <rocket::error::LaunchError as core::ops::drop::Drop>::drop::he8c067697eb81513
                               at /home/tyoc213/Documents/explorations/202106/Rocket/core/lib/src/error.rs:214:17
  15:     0x564a30fc63b7 - core::ptr::drop_in_place<rocket::error::LaunchError>::h1443ef81a3158d4b
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/core/src/ptr/mod.rs:192:1
  16:     0x564a30fe0657 - todo::main::h4cbf9e10af3492bc
                               at /home/tyoc213/Documents/explorations/202106/Rocket/examples/todo/src/main.rs:103:22
  17:     0x564a30fc53cb - core::ops::function::FnOnce::call_once::h218c98adea030def
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/core/src/ops/function.rs:227:5
  18:     0x564a30fc4b8e - std::sys_common::backtrace::__rust_begin_short_backtrace::h2560f962366ab607
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/sys_common/backtrace.rs:125:18
  19:     0x564a30fb1481 - std::rt::lang_start::{{closure}}::h524ee844e60c154b
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/rt.rs:49:18
  20:     0x564a3180e709 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb7e6faf34af9846c
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/core/src/ops/function.rs:259:13
  21:     0x564a3180e709 - std::panicking::try::do_call::h296b61164472fbd0
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/panicking.rs:401:40
  22:     0x564a3180e709 - std::panicking::try::h5af03c5219a60f37
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/panicking.rs:365:19
  23:     0x564a3180e709 - std::panic::catch_unwind::hb1897a05d4c85a03
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/panic.rs:434:14
  24:     0x564a3180e709 - std::rt::lang_start_internal::h36d625ff75238a29
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/rt.rs:34:21
  25:     0x564a30fb1460 - std::rt::lang_start::hfa1c647d27873921
                               at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/rt.rs:48:5
  26:     0x564a30fe39ec - main
  27:     0x7f1148b780b3 - __libc_start_main
  28:     0x564a30fad06e - _start
  29:                0x0 - <unknown>
```

**Comment by jebrosen** [comment] 2021-06-07 04:23
> ```
> QueryError(DatabaseError(__Unknown, "near \"OR\": syntax error"))\
> ```

This appears to be the root of the problem, but I have tried and failed to find an "OR" clause anywhere in the migrations file or in diesel's migrations infrastructure.

* Have you made any modifications to the example?
* Can you try deleting the database (`todo/db/db.sqlite`) in case there is a an existing database causing issues?
* What Linux distribution is this, with what version of sqlite installed? (the package name may be different: sqlite3, libsqlite3-dev, etc.)

**Comment by SergioBenitez** [comment] 2021-06-07 04:56
I also cannot reproduce this. The CI is also unable to reproduce this.

**Comment by SergioBenitez** [comment] 2021-06-08 03:32
Closing this out as this appears unrelated to Rocket or its examples and instead an incorrect local modification. Please do comment if this is incorrect and you can reproduce this issue on a clean clone of the repository.

**Closed by SergioBenitez** 2021-06-08 03:32 UTC
Labels: triage
