### ISSUE TITLE
rocket::ignite does not fail if its desired port is in use

### ISSUE THREAD

**Issue by ndarilek** [SergioBenitez/Rocket#260] opened 2017-04-15 17:25 UTC
Rocket/codegen version: 0.2.4
Rust: rustc 1.18.0-nightly (bbdaad0dc 2017-04-14)

If you have one Rocket server running on port 8000, then launch another, the second claims to work even though it can't possibly since port 8000 is already in use.

I just hit this running one Rocket example in one terminal then forgetting about it. I then launched the Hello World example, which claimed to be running, and couldn't figure out why it kept 404ing on me. It wasn't until I found and killed the other server that I realized what was up.

**Comment by SergioBenitez** [comment] 2017-04-16 01:00
This is a duplicate of #209. Please refer to that issue for details on the matter.

**Closed by SergioBenitez** 2017-04-16 01:00 UTC
Labels: duplicate
