### ISSUE TITLE
impl FromFormValue for Option<T>: weird behavior with Enums via Serde Deserializer

### ISSUE THREAD

**Issue by valeriansaliou** [SergioBenitez/Rocket#428] opened 2017-09-14 11:15 UTC
Hey,

Rocket exposes a weird behavior w/ the `FromForm` derive on GET query parameters that are `Option<T>`, when passing a `T` value which is Enum-typed. The enum implements Serde's Deserialize trait to resolve to an enum value.

Overall, Enums + `FromForm` works. However, if the parameter is `Option<T>` where `T` is an Enum, and an unknown Enum value is passed in a request, no `BadRequest` error will be emitted from Rocket (which is the expected behavior, IMHO). Rather, the `Option<T>` will resolve to `None`, and thus the GET query data will be accepted.

**I suggest that if an Err() occurs when parsing the contained `T` value, the whole form parsing should fail and thus emit a `BadRequest`, rather than ignoring the parser error and setting the container `Option` to `None`.**

As in Rust, there is no way (that I know of) of overriding a trait impl., this issue cannot be solved locally (if this is the behavior you expected of it).

Origin: [lib/src/request/form/from_form_value.rs#L210](https://github.com/SergioBenitez/Rocket/blob/master/lib/src/request/form/from_form_value.rs#L210)

## Behaviors (current / expected):

* [OK] T where T is an Enum, wrong value given, this should break - Current: resolves to `BadRequest ` / Expected: `BadRequest`
* [OK] Option<T> where T is an Enum, no value provided, this should resolve to None - Current: resolves to `None` / Expected: `None `
* [OK] Option<T> where T is an Enum, valid value provided, this should resolve to Some(Enum::Value) - Current: resolves to `Enum::Value` / Expected: `Enum::Value`
* **[NOT OK] Option<T> where T is an Enum, invalid value provided, this should break - Current: resolves to `None` / Expected: `BadRequest`**

## Environment:

**Rocket version:** v0.3.2
**OS:** macOS Sierra

## Fix?

I'd suggest patching the trait impl as such (untested):

```diff
impl<'v, T: FromFormValue<'v>> FromFormValue<'v> for Option<T> {
    type Error = !;

    #[inline(always)]
    fn from_form_value(v: &'v RawStr) -> Result<Self, Self::Error> {
+       if v.is_empty() {
+           Ok(None)
+       } else {
            match T::from_form_value(v) {
                Ok(v) => Ok(Some(v)),
-               Err(_) => Ok(None),
+               Err(e) => Err(e),
            }
+       }
    }

    #[inline(always)]
    fn default() -> Option<Option<T>> {
        Some(None)
    }
}
```

That way, we bypass parsing if no value is provided (as that's the goal of the `Option`). And, we properly propagate any parsing error if there's a value and the parsing fails.

## Snippets:

_Given an enum for a person's genre:_

```rust
enum Genre {
    Male,
    Female
}
```

_Serde impls:_

```rust
use std::{fmt, str};
use std::io::Write;
use std::error::Error;
use serde::{Serialize, Serializer, Deserialize, Deserializer};
use serde::de::{Visitor, Unexpected, Error as DeserializeError};

impl<'d> Deserialize<'d> for Genre {
    fn deserialize<D: Deserializer<'d>>(deserializer: D) -> Result<Genre, D::Error> {
        struct FieldVisitor;

        impl<'d> Visitor<'d> for FieldVisitor {
            type Value = Genre;

            fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
                formatter.write_str("a valid value")
            }

            fn visit_str<E: DeserializeError>(self, value: &str) -> Result<Self::Value, E> {
                match Genre::from_bytes(value.as_bytes()) {
                    Some(inner) => Ok(inner),
                    None => Err(E::invalid_type(Unexpected::Enum, &self)),
                }
            }
        }

        deserializer.deserialize_str(FieldVisitor)
    }
}
```

_Rocket impls:_

```rust
impl<'v> FromFormValue<'v> for Genre {
    type Error = &'v RawStr;

    fn from_form_value(form_value: &'v RawStr) ->
        Result<Genre, &'v RawStr> {
        match Genre::from_bytes(form_value.as_bytes()) {
            Some(value) => Ok(value),
            _ => Err(form_value),
        }
    }
}
```

_Argument struct:_

```rust
#[derive(FromForm, Validate, Serialize)]
struct Args {
    person_gender: Option<Gender>
}
```

_Calls:_

* `/route?person_gender=male` — OK -> Some(Gender::Male)
* `/route?person_gender=female` — OK -> Some(Gender::Female)
* `/route` — OK -> None
* `/route?person_gender=alien` — NOK -> None

**Comment by SergioBenitez** [comment] 2017-09-14 22:29
This is how `Option<T>` works; if `T` fails to parse for any reason, you get a `None`. You're observing the expected behavior. You can easily create another type, say `Maybe`, that implements `FromFormValue` in the way you'd like. Alternatively, you can have a `None` variant for `Gender` and change the implementation of `FromFormValue` to work the way you like.

What does you route look like, by the way?

**Comment by valeriansaliou** [comment] 2017-09-15 05:06
Oh, okay, thanks. Sounds good for me w/ a `Maybe<T>`.

On your route question, the route pattern is as follow:

`#[get("/search/lookup/people/<page_number>?<args>")]`

Where `args` is (a lot of optional GET params, used as a REST route):

```rust
#[derive(FromForm)]
pub struct SearchLookupPeopleArgs {
    person_first_name: Option<String>,
    person_last_name: Option<String>,
    person_description: Option<String>,
    person_gender: Option<PrGenderEnum>,
    person_timezone: Option<String>,
    person_email: Option<String>,
    person_phone: Option<String>,
    person_address_street: Option<String>,
    person_address_postcode: Option<String>,
    person_address_city: Option<String>,
    person_address_region: Option<String>,
    person_address_country: Option<CountryEnum>,

    // (...) 20+ fields trimmed
}
```

**Comment by SergioBenitez** [comment] 2017-12-20 02:34
Looks like we can close this. Please let me know if I've misinterpreted.

**Closed by SergioBenitez** 2017-12-20 02:34 UTC
Labels: question
