### ISSUE TITLE
[Feature Request] Allow route handlers to be templated

### ISSUE THREAD

**Issue by Hugal31** [SergioBenitez/Rocket#858] opened 2018-12-11 12:58 UTC
# Feature request

The routes should be able to accept generic handlers. Example:

```rust
#[get("/<id>")]
fn foo<I>(id: I)
where
  I: for<'r> FromParam<'r> + Display
{
    println!("Id = {}", id);
}

fn main() {
    rocket::ignite()
        .mount("/", routes![foo<u8>])
        .launch()
}
```

  1. Why you believe this feature is necessary.

I want to compile my application for multiple use scenarios. The main idea I have is to allow my application to use different kinds of databases, and still take advantages of zero-cost abstraction.

  2. A convincing use-case for this feature.

For instance, we could have:
```rust
trait UserService {
  fn get_user(&self, id: u32) -> Result<User>;
}

#[get("/<id>")]
fn get_user<US>(id: u32, user_service: State<UserService>) -> Result<Json<User>>
where
  US: UserService {
  user_service.get_user(id).map(|u| Json(u))
}
```

So it would be possible to use PostgreSQL or MySQL on production, and a custom mock of UserService for unit tests.

  3. Why this feature can't or shouldn't exist outside of Rocket.

Rockets allow route handlers to fetch parameters from the request and the global state with the types of the parameters of the handler. It is up to Rocket to allow those parameters to be templatized.

# Implementation

The proc macro for `#[get] / #[post] / ...` could simply copy the types parameters and their constraints. For instance, for the first example with the `foo` handler, the macro would generate this:

```rust
#[doc = r" Rocket code generated wrapping route function."]
fn rocket_route_fn_foo<'_b, I>(
    __req: &'_b ::rocket::Request,
    __data: ::rocket::Data,
) -> ::rocket::handler::Outcome<'_b>
where I: for<'_foo_r> rocket::request::FromParam<'_foo_r> + Display
{
    ...
```

For the creation of the `StaticRouteInfo` and the `routes!` macro, however, I am not sure how to implement it, since we could not create one `StaticRouteInfo`.

**Comment by SergioBenitez** [comment] 2018-12-11 20:21
This is a duplicate of #408.

**Closed by SergioBenitez** 2018-12-11 20:21 UTC
